import { createContext, useContext, useEffect, useState, type ReactNode } from 'react'

type Language = 'es' | 'en'

interface Translations {
  [key: string]: string | Translations
}

const translations: Record<Language, Translations> = {
  es: {
    dashboard: 'Dashboard',
    instances: 'Instancias',
    containers: 'Contenedores',
    images: 'Imágenes',
    settings: 'Configuración',
    logout: 'Cerrar sesión',
    globalStatus: 'Estado global del cluster Docker',
    globalSystemStatus: 'Estado global del sistema',
    activeHosts: 'Hosts Activos',
    online: 'en línea',
    offline: 'fuera de línea',
    totalContainers: 'Total Contenedores',
    running: 'En ejecución',
    stopped: 'Detenidos',
    exitedCreated: '(Detenidos/Creados)',
    avgCpuUsage: 'CPU promedio',
    avgMemoryUsage: 'Memoria promedio',
    avgDiskUsage: 'Disco promedio',
    clusterAverage: 'Promedio del cluster',
    monitoredMachines: 'Máquinas monitoreadas',
    clusterStatus: 'Estado de los cluster',
    machines: 'máquinas',
    noInstances: 'No hay instancias registradas',
    alerts: 'Alertas',
    hostsNeedAttention: 'hosts requieren atención',
    systemHealthOverview: 'Salud del Sistema',
    resourceUsageByHost: 'Uso de recursos por host',
    noHostMetrics: 'No hay métricas del host disponibles',
    systemAlerts: 'Alertas del Sistema',
    systemAlertsDescription: 'Alertas y advertencias del estado de los hosts',
    noSystemAlerts: 'No hay alertas del sistema. Todo se encuentra en condiciones normales.',
    hostOfflineAlert: 'Host fuera de línea',
    cpuHighAlert: 'Uso de CPU crítico: {value}%',
    cpuWarningAlert: 'Uso de CPU elevado: {value}%',
    memoryHighAlert: 'Uso de memoria crítico: {value}%',
    memoryWarningAlert: 'Uso de memoria elevado: {value}%',
    diskHighAlert: 'Uso de disco crítico: {value}%',
    diskWarningAlert: 'Uso de disco elevado: {value}%',
    loadHighAlert: 'Carga del sistema elevada: {value}',
    serverTransactionDegradedAlert: 'Transacciones degradadas en {hostname}: {service} falló {count} peticiones',
    systemProcesses: 'Procesos del Sistema',
    noProcesses: 'No hay información de procesos disponibles',
    memoryUsage: 'Memoria usada',
    runningContainers: 'Contenedores activos',
    healthMatrix: 'Matriz de Salud',
    component: 'Componente',
    normal: 'Normal',
    resourceUsage: 'Uso de Recursos',
    critical: 'Críticas',
    warning: 'Advertencias',
    noAlerts: 'Sin alertas',
    backToInstances: 'Volver a instancias',
    alertsOf: 'Alertas de',
    processes: 'Procesos',
    process: 'Proceso',
    systemProcessesDescription: 'Procesos del sistema de los hosts registrados',
    processesOf: 'Procesos de',
    totalProcesses: 'Total de procesos',
    topProcessesShown: 'Procesos mostrados',
    searchProcessPlaceholder: 'Buscar proceso por nombre o PID...',
    searchResultsCount: '{count} coincidencias encontradas',
    clear: 'Limpiar',
    packages: 'Paquetes',
    packagesDescription: 'Gestión de paquetes del sistema de los hosts registrados',
    packagesOf: 'Paquetes de',
    managePackages: 'Gestionar paquetes',
    manageContainers: 'Gestionar contenedores',
    containersOf: 'Contenedores de',
    manageImages: 'Gestionar imágenes',
    imagesOf: 'Imágenes de',
    searchPackage: 'Buscar paquete...',
    upgradableOnly: 'Solo actualizables',
    refreshPackages: 'Refrescar lista',
    upgradePackages: 'Actualizar paquetes',
    removePackages: 'Eliminar paquetes',
    removeSelected: 'Eliminar seleccionados',
    packageSelected: 'paquete seleccionado',
    packagesSelected: 'paquetes seleccionados',
    removePackagesConfirmSingular: '¿Deseas eliminar el paquete seleccionado? Esta acción no se puede deshacer.',
    removePackagesConfirmPlural: '¿Deseas eliminar los paquetes seleccionados? Esta acción no se puede deshacer.',
    removePackagesWarning: 'Esta operación eliminará software del sistema.',
    purgePackages: 'Eliminar también archivos de configuración (purge)',
    purgeDescription: 'Se eliminará el paquete y todos sus archivos de configuración.',
    removeDescription: 'Se eliminará el paquete pero se conservarán los archivos de configuración.',
    connectionHistory: 'Historial de conexión',
    noConnectionHistory: 'No hay historial de conexión disponible',
    operationResult: 'Resultado de la operación',
    hideOutput: 'Ocultar salida',
    showOutput: 'Ver salida',
    noPackages: 'No se encontraron paquetes',
    installed: 'Instalado',
    architecture: 'Arquitectura',
    source: 'Origen',
    packageManager: 'Gestor de paquetes',
    instanceOverview: 'Visión General de Instancias',
    hostsRegistered: 'Hosts Registrados',
    status: 'Estado',
    hostname: 'Hostname',
    serviceID: 'Service ID',
    containersCount: 'Contenedores',
    runningCount: 'Corriendo',
    lastHeartbeat: 'Último Heartbeat',
    actions: 'Acciones',
    viewDetails: 'Ver Detalles',
    recentContainers: 'Contenedores Recientes',
    stateChanges: 'Cambios de Estado',
    start: 'Iniciar',
    stop: 'Detener',
    restart: 'Reiniciar',
    remove: 'Eliminar',
    containerStates: 'Distribución de Estados de Contenedores',
    noContainers: 'No hay contenedores para mostrar',
    allCluster: 'Todo el Cluster',
    hosts: 'hosts',
    live: 'En vivo',
    search: 'Buscar',
    searchImage: 'Buscar imagen...',
    searchImageExample: 'ej: home assistant',
    imageNameExample: 'ej: nginx:latest',
    searchImageButton: 'Buscar imagen',
    searchImageTitle: 'Buscar imagen en Docker Hub',
    searchOnDockerHub: 'Buscar en Docker Hub',
    pressEnterToSearch: 'Escribe y presiona Enter o haz clic en Buscar',
    searchImageError: 'Error al buscar imágenes en Docker Hub',
    noSearchResults: 'No se encontraron imágenes',
    official: 'Oficial',
    noDescription: 'Sin descripción',
    pullCount: 'Descargas',
    defaultTag: 'Tag por defecto',
    imageToDownload: 'Imagen a descargar',
    searchContainer: 'Buscar contenedor...',
    host: 'Host',
    size: 'Tamaño',
    created: 'Creada',
    id: 'ID',
    image: 'Imagen',
    state: 'Estado',
    ports: 'Puertos',
    allStates: 'Todos los estados',
    noImages: 'No se encontraron imágenes',
    noContainersFound: 'No se encontraron contenedores',
    noRecentContainers: 'No hay contenedores recientes',
    loadImage: 'Cargar imagen',
    update: 'Actualizar',
    cancel: 'Cancelar',
    download: 'Descargar',
    configuration: 'Configuración',
    managePreferences: 'Administra la configuración y preferencias de tu cuenta',
    dataRetention: 'Retención de Datos y Almacenamiento',
    dataRetentionDesc: 'Define por cuánto tiempo conservar el historial de métricas y red para optimizar la base de datos',
    retentionDays: 'Período de Conservación',
    days3: '3 Días',
    days7: '7 Días (Recomendado)',
    days14: '14 Días',
    days30: '30 Días',
    days60: '60 Días',
    runCleanupNow: 'Limpiar Base de Datos Ahora',
    saveRetention: 'Guardar Política',
    retentionSaved: 'Política de retención actualizada con éxito',
    cleanupSuccess: 'Limpieza completada con éxito',
    basics: 'Básicos',
    profile: 'Perfil',
    manageAccountInfo: 'Administra la información de tu cuenta',
    password: 'Contraseña',
    setPassword: 'Establece una contraseña para proteger tu cuenta',
    administrator: 'Administrador',
    verySecure: 'Muy segura',
    darkMode: 'Modo oscuro',
    useDarkTheme: 'Usa el tema oscuro en toda la aplicación',
    enabled: 'Activado',
    disabled: 'Desactivado',
    notifications: 'Notificaciones',
    enableNotifications: 'Habilitar notificaciones',
    receiveAlerts: 'Recibe alertas sobre cambios de estado y eventos',
    language: 'Idioma',
    interfaceLanguage: 'Idioma de la interfaz',
    chooseLanguage: 'Elige el idioma de la interfaz',
    system: 'Sistema',
    systemInfo: 'Información sobre la versión y tecnologías',
    version: 'Versión',
    backend: 'Backend',
    frontend: 'Frontend',
    session: 'Sesión',
    closeSession: 'Cerrar sesión',
    closeCurrentSession: 'Cierra la sesión actual',
    edit: 'Editar',
    general: 'General',
    instance: 'Instancia',
    name: 'Nombre',
    of: 'de',
    command: 'Comando',
    environmentVariables: 'Variables de entorno',
    volumes: 'Volúmenes',
    labels: 'Etiquetas',
    rename: 'Renombrar',
    noData: 'Sin datos',
    cpu: 'CPU',
    cpuCores: 'Núcleos CPU',
    memory: 'Memoria',
    disk: 'Disco',
    loadAverage: 'Carga',
    uptime: 'Uptime',
    platform: 'Plataforma',

    // Estados de contenedores
    stateRunning: 'En ejecución',
    stateExited: 'Detenido',
    stateCreated: 'Creado',
    statePaused: 'Pausado',
    stateRestarting: 'Reiniciando',
    stateRemoving: 'Eliminando',
    stateDead: 'Muerto',
    stateUnknown: 'Desconocido',
    stateHealthy: 'Saludable',
    stateUp: 'Activo',
    stateDown: 'Inactivo',
    stateError: 'Error',
    stateWarning: 'Advertencia',
    stateStopped: 'Detenido',
    stateUnhealthy: 'No saludable',
    stateCrashLoopBackOff: 'CrashLoopBackOff',
    stateOOMKilled: 'OOMKilled',

    // Container detail panel
    containerDetails: 'Detalles del contenedor',
    generalInfo: 'Información General',
    events: 'Eventos',
    logs: 'Logs',
    noEvents: 'No hay eventos',
    noLogs: 'No hay logs disponibles',
    copyLogs: 'Copiar logs',
    downloadLogs: 'Descargar logs',
    autoScroll: 'Scroll automático',
    showTimestamps: 'Mostrar timestamps',
    refresh: 'Refrescar',
    lines: 'líneas',

    // Navegación runtime
    dockerContainers: 'Docker Containers',
    dockerImages: 'Docker Images',
    selectRuntime: 'Selecciona una tecnología de contenedores',
    comingSoon: 'Próximamente',
    notAvailable: 'No disponible aún',
    total: 'Total',
    allDockerContainers: 'Todos los contenedores Docker del cluster',
    registeredHosts: 'Hosts registrados en el cluster',
    selectDevice: 'Seleccionar Dispositivo',
    chooseInstance: '-- Selecciona una máquina --',
    noDeviceSelectedTitle: 'No se ha seleccionado ninguna máquina',
    noDeviceSelectedDesc: 'Por favor, selecciona una máquina o dispositivo en el menú superior para ver y gestionar sus contenedores.',
    noContainersInInstance: 'No hay contenedores en esta instancia',
    containerNotFound: 'Contenedor no encontrado',
    instanceNotFound: 'Instancia no encontrada',
    hostMetrics: 'Métricas del host',
    dockerImagesAvailable: 'Imágenes Docker disponibles en el cluster',
    autoRemove: 'Auto-eliminación',
    removeContainer: 'Eliminar contenedor',
    removeImage: 'Eliminar imagen',
    removeContainerConfirm: '¿Deseas eliminar el contenedor "{name}"? Esta acción no se puede deshacer.',
    removeImageConfirm: '¿Deseas borrar la imagen "{name}"? Esta acción no se puede deshacer.',
    errorRemovingContainer: 'Error al eliminar el contenedor',
    errorRemovingImage: 'Error al eliminar la imagen',
    errorStartingContainer: 'Error al iniciar el contenedor',
    errorStoppingContainer: 'Error al detener el contenedor',
    errorRestartingContainer: 'Error al reiniciar el contenedor',
    errorRenamingContainer: 'Error al renombrar el contenedor',
    errorUpdatingImage: 'Error al actualizar la imagen',
    errorDownloadingImage: 'Error al descargar la imagen',
    selectContainerTechnology: 'Selecciona una tecnología de contenedores',
    runtimeDescription: 'Gestiona contenedores e imágenes del runtime {runtime} de tus hosts registrados.',
    dockerDescription: 'Gestiona contenedores e imágenes del runtime Docker de tus hosts registrados.',
    podmanDescription: 'Soporte para contenedores rootless e imágenes Podman próximamente.',
    rootless: 'rootless',

    // Auth
    welcomeBack: 'Bienvenido de nuevo',
    loginSubtitle: 'Inicia sesión para continuar con Orchestrack',
    email: 'Correo electrónico',
    emailPlaceholder: 'tu@email.com',
    passwordPlaceholder: '••••••••',
    confirmPassword: 'Confirmar contraseña',
    confirmPasswordPlaceholder: '••••••••',
    loggingIn: 'Iniciando sesión...',
    signingUp: 'Creando cuenta...',
    login: 'Iniciar sesión',
    signUp: 'Crear cuenta',
    createAccount: 'Crear cuenta',
    signupSubtitle: 'Regístrate para comenzar con Orchestrack',
    noAccount: '¿No tienes cuenta?',
    alreadyHaveAccount: '¿Ya tienes cuenta?',
    passwordsDoNotMatch: 'Las contraseñas no coinciden',
    statePending: 'Pendiente',
    addMachine: 'Agregar máquina',
    addDevice: 'Agregar dispositivo',
    addDeviceDescription: 'Registra un nuevo dispositivo/agente en la red de Orchestrack',
    approve: 'Aprobar',
    approving: 'Aprobando...',
    registrationToken: 'Token de Registro',
    generateRegistrationToken: 'Generar Token',
    generatingToken: 'Generando...',
    runCommandOnDevice: 'Ejecuta este comando en la terminal del dispositivo:',
    copied: 'Copiado',
    copy: 'Copiar',
    close: 'Cerrar',
    tokenExpiryNotice: 'Este token expirará en 24 horas y solo se puede utilizar una vez.',
    markAllAsRead: 'Marcar todas como leídas',
    noNotifications: 'Sin notificaciones',
    rememberMe: 'Recuérdame',
    forgotPassword: '¿Olvidaste tu contraseña?',
    showPassword: 'Mostrar contraseña',
    hidePassword: 'Ocultar contraseña',
    loginTagline: 'Gestiona tu infraestructura desde un solo lugar.',
    loginDescription: 'Inicia sesión para acceder a tu panel de control y administrar tus dispositivos.',
    orLoginWith: 'O inicia sesión con',
    forgotPasswordTitle: 'Recuperar contraseña',
    forgotPasswordSubtitle: 'Ingresa tu correo electrónico y te enviaremos las instrucciones para restablecer tu contraseña.',
    sendInstructions: 'Enviar instrucciones',
    sending: 'Enviando...',
    backToLogin: 'Volver al inicio de sesión',
    checkYourEmail: 'Revisa tu correo electrónico',
    resetEmailSent: 'Si existe una cuenta con ese correo, recibirás un enlace para restablecer tu contraseña.',
    passwordRequirements: 'La contraseña debe tener al menos 6 caracteres',
    signupTagline: 'Comienza a monitorear tu infraestructura hoy.',
    signupDescription: 'Crea una cuenta para acceder al panel de control y gestionar tus dispositivos.',

    // Incidentes y Diagnóstico de Causa Raíz
    incidents: 'Incidentes',
    incidentDiagnostic: 'Diagnóstico de Incidente',
    rootCause: 'Causa Raíz',
    rootCauseTrigger: 'Causa Raíz Detonante',
    origin: 'Origen',
    timeline: 'Línea de Tiempo',
    incidentEvents: 'Eventos del Incidente',
    noIncidents: 'No hay incidentes registrados',
    incidentStatusOpen: 'Abierto',
    incidentStatusResolved: 'Resuelto',
    propagation: 'Propagación',
    impact: 'Impacto',
    eventSequence: 'Secuencia de Eventos',
    viewDiagnostic: 'Ver Diagnóstico',
    closeDiagnostic: 'Cerrar Diagnóstico',
    inHost: 'en Host',
    incidentCreated: 'Incidente creado',
    incidentUpdated: 'Incidente actualizado',
    incidentResolved: 'Incidente resuelto',
    noTimelineEvents: 'No hay eventos en la línea de tiempo',
    eventType: 'Tipo de evento',
    sequence: 'Secuencia',

    // Propagación de fallas y Blast Radius (T-014)
    blastRadius: 'Radio de Impacto',
    affectedServers: 'Servidores afectados',
    affectedContainers: 'Contenedores afectados',
    propagationDepth: 'Profundidad de propagación',
    serversAffected: 'servidores afectados',
    containersAffected: 'contenedores afectados',
    from: 'Desde',
    to: 'Hacia',
    propagationMap: 'Mapa de Propagación',
    noPropagationData: 'No hay datos de propagación',
    cascadeFailure: 'Falla en cascada',
    impactSummary: 'Resumen de Impacto',
    totalCluster: 'Total del clúster',

    // Árbol de impacto multi-host en tiempo real (T-016)
    multiHostImpact: 'Árbol de Impacto Multi-Host',
    livePropagation: 'Propagación en Vivo',
    infrastructureAffected: 'Infraestructura afectada',
    affectedHosts: 'Hosts afectados',
    propagationInProgress: 'Propagación en progreso',
    originServer: 'Servidor origen',
    noPropagationLive: 'No hay propagación activa',

    // Transacciones y Servicios Afectados (T-021)
    affectedTransactionsAndServices: 'Transacciones y Servicios Afectados',
    noTransactionImpact: 'No hay transacciones afectadas registradas para este incidente',
    byCategory: 'Por Categoría',
    byServer: 'Por Servidor',
    failedRequests: 'fallos',
    errors: 'errores',
    device: 'Dispositivo',
    noCategoryData: 'No hay datos por categoría',
    noServerTransactionData: 'No hay datos de transacciones por servidor',
    totalFailedRequests: 'Total de peticiones fallidas',
    affectedCategories: 'Categorías afectadas',

    // Topología de contenedores (T-026)
    containerTopology: 'Topología de Contenedores',
    containerNetworkGraph: 'Grafo de Red de Contenedores',
    noContainerTopology: 'No se detectaron contenedores conectados en red en este servidor',
    containersConnected: 'contenedores conectados',
    networksDetected: 'redes detectadas',
    networkShared: 'Red compartida',
    composeLink: 'Enlace Compose',
    refreshTopology: 'Refrescar topología',
    containerNetworkDescription: 'Contenedores unidos por una misma red Docker. La etiqueta indica la red y el tipo de vínculo entre ambos.',
    servicesNetwork: 'Red de servicios',

    // Mapa de topología multi-servidor (T-017)
    topology: 'Topología',
    topologyMap: 'Mapa de Topología',
    multiServerTopology: 'Topología Multi-Servidor',
    networkMap: 'Mapa de Red',
    serverNodes: 'Nodos de servidor',
    containerNodes: 'Nodos de contenedor',
    originNode: 'Nodo origen',
    propagationRoute: 'Ruta de propagación',
    selectNode: 'Selecciona un nodo',
    nodeMetrics: 'Métricas del nodo',
    nodeContainers: 'Contenedores del nodo',
    nodeEvents: 'Eventos del nodo',
    connectedServers: 'Servidores conectados',
    clickNodeDetails: 'Haz clic en un nodo para ver detalles',
    healthy: 'Saludable',
    degraded: 'Degradado',
    down: 'Caído',
    backingEvidence: 'Evidencia que lo Respalda',
    containerLogs: 'Logs de Contenedores',
    hostMetricsSnapshot: 'Snapshot de Métricas',
    systemEventsDockerLogs: 'Logs del Daemon Docker',
    exportForensicBundle: 'Exportar Paquete Forense (ZIP)',
    waitingForEvidence: 'Esperando recolección de evidencias...',
    evidenceAvailable: 'Evidencia forense disponible para análisis.',
    noEvidenceAvailable: 'No hay evidencias disponibles para este incidente.',
  },
  en: {
    dashboard: 'Dashboard',
    instances: 'Instances',
    containers: 'Containers',
    images: 'Images',
    settings: 'Settings',
    logout: 'Logout',
    globalStatus: 'Global Docker Cluster Status',
    globalSystemStatus: 'Global System Status',
    activeHosts: 'Active Hosts',
    online: 'Online',
    offline: 'Offline',
    totalContainers: 'Total Containers',
    running: 'Running',
    stopped: 'Stopped',
    exitedCreated: '(Exited/Created)',
    avgCpuUsage: 'Avg CPU Usage',
    avgMemoryUsage: 'Avg Memory Usage',
    avgDiskUsage: 'Avg Disk Usage',
    clusterAverage: 'Cluster average',
    monitoredMachines: 'Monitored machines',
    clusterStatus: 'Cluster status',
    machines: 'machines',
    noInstances: 'No instances registered',
    alerts: 'Alerts',
    hostsNeedAttention: 'hosts need attention',
    systemHealthOverview: 'System Health Overview',
    resourceUsageByHost: 'Resource usage by host',
    noHostMetrics: 'No host metrics available',
    systemAlerts: 'System Alerts',
    systemAlertsDescription: 'Alerts and warnings about hosts health',
    noSystemAlerts: 'No system alerts. Everything is running within normal parameters.',
    hostOfflineAlert: 'Host offline',
    cpuHighAlert: 'Critical CPU usage: {value}%',
    cpuWarningAlert: 'High CPU usage: {value}%',
    memoryHighAlert: 'Critical memory usage: {value}%',
    memoryWarningAlert: 'High memory usage: {value}%',
    diskHighAlert: 'Critical disk usage: {value}%',
    diskWarningAlert: 'High disk usage: {value}%',
    loadHighAlert: 'High system load: {value}',
    serverTransactionDegradedAlert: 'Degraded transactions on {hostname}: {service} failed {count} requests',
    systemProcesses: 'System Processes',
    noProcesses: 'No process information available',
    memoryUsage: 'Memory used',
    runningContainers: 'Running containers',
    healthMatrix: 'Health Matrix',
    component: 'Component',
    normal: 'Normal',
    resourceUsage: 'Resource Usage',
    critical: 'Critical',
    warning: 'Warnings',
    noAlerts: 'No alerts',
    backToInstances: 'Back to instances',
    alertsOf: 'Alerts of',
    processes: 'Processes',
    process: 'Process',
    systemProcessesDescription: 'System processes from registered hosts',
    processesOf: 'Processes of',
    totalProcesses: 'Total processes',
    topProcessesShown: 'Processes shown',
    searchProcessPlaceholder: 'Search process by name or PID...',
    searchResultsCount: '{count} matches found',
    clear: 'Clear',
    packages: 'Packages',
    packagesDescription: 'Manage system packages from registered hosts',
    packagesOf: 'Packages of',
    managePackages: 'Manage packages',
    manageContainers: 'Manage containers',
    containersOf: 'Containers of',
    manageImages: 'Manage images',
    imagesOf: 'Images of',
    searchPackage: 'Search package...',
    upgradableOnly: 'Upgradable only',
    refreshPackages: 'Refresh list',
    upgradePackages: 'Upgrade packages',
    removePackages: 'Remove packages',
    removeSelected: 'Remove selected',
    packageSelected: 'package selected',
    packagesSelected: 'packages selected',
    removePackagesConfirmSingular: 'Do you want to remove the selected package? This action cannot be undone.',
    removePackagesConfirmPlural: 'Do you want to remove the selected packages? This action cannot be undone.',
    removePackagesWarning: 'This operation will remove software from the system.',
    purgePackages: 'Also remove configuration files (purge)',
    purgeDescription: 'The package and all its configuration files will be removed.',
    removeDescription: 'The package will be removed but configuration files will be kept.',
    connectionHistory: 'Connection history',
    noConnectionHistory: 'No connection history available',
    operationResult: 'Operation result',
    hideOutput: 'Hide output',
    showOutput: 'Show output',
    noPackages: 'No packages found',
    installed: 'Installed',
    architecture: 'Architecture',
    source: 'Source',
    packageManager: 'Package manager',
    instanceOverview: 'Instances Overview',
    hostsRegistered: 'Hosts Registered',
    status: 'Status',
    hostname: 'Hostname',
    serviceID: 'Service ID',
    containersCount: 'Containers',
    runningCount: 'Running',
    lastHeartbeat: 'Last Heartbeat',
    actions: 'Actions',
    viewDetails: 'View Details',
    recentContainers: 'Recent Containers',
    stateChanges: 'State Changes',
    start: 'Start',
    stop: 'Stop',
    restart: 'Restart',
    remove: 'Remove',
    containerStates: 'Container States Distribution',
    noContainers: 'No containers to display',
    allCluster: 'All Cluster',
    hosts: 'hosts',
    live: 'Live',
    search: 'Search',
    searchImage: 'Search image...',
    searchImageExample: 'e.g. home assistant',
    imageNameExample: 'e.g. nginx:latest',
    searchImageButton: 'Search image',
    searchImageTitle: 'Search image on Docker Hub',
    searchOnDockerHub: 'Search on Docker Hub',
    pressEnterToSearch: 'Type and press Enter or click Search',
    searchImageError: 'Error searching images on Docker Hub',
    noSearchResults: 'No images found',
    official: 'Official',
    noDescription: 'No description',
    pullCount: 'Pulls',
    defaultTag: 'Default tag',
    imageToDownload: 'Image to download',
    searchContainer: 'Search container...',
    host: 'Host',
    size: 'Size',
    created: 'Created',
    id: 'ID',
    image: 'Image',
    state: 'State',
    ports: 'Ports',
    allStates: 'All states',
    noImages: 'No images found',
    noContainersFound: 'No containers found',
    noRecentContainers: 'No recent containers',
    loadImage: 'Load image',
    update: 'Update',
    cancel: 'Cancel',
    download: 'Download',
    configuration: 'Configuration',
    managePreferences: 'Manage your account settings and preferences',
    dataRetention: 'Data Retention & Storage',
    dataRetentionDesc: 'Define how long to keep metrics and network history to optimize database storage',
    retentionDays: 'Retention Period',
    days3: '3 Days',
    days7: '7 Days (Recommended)',
    days14: '14 Days',
    days30: '30 Days',
    days60: '60 Days',
    runCleanupNow: 'Clean Database Now',
    saveRetention: 'Save Policy',
    retentionSaved: 'Retention policy updated successfully',
    cleanupSuccess: 'Cleanup completed successfully',
    basics: 'Basics',
    profile: 'Profile',
    manageAccountInfo: 'Manage your account information',
    password: 'Password',
    setPassword: 'Set a password to protect your account',
    administrator: 'Administrator',
    verySecure: 'Very secure',
    darkMode: 'Dark mode',
    useDarkTheme: 'Use dark theme across the entire application',
    enabled: 'Enabled',
    disabled: 'Disabled',
    notifications: 'Notifications',
    enableNotifications: 'Enable notifications',
    receiveAlerts: 'Receive alerts about state changes and events',
    language: 'Language',
    interfaceLanguage: 'Interface language',
    chooseLanguage: 'Choose the language for the interface',
    system: 'System',
    systemInfo: 'Information about version and technologies',
    version: 'Version',
    backend: 'Backend',
    frontend: 'Frontend',
    session: 'Session',
    closeSession: 'Log out',
    closeCurrentSession: 'Close your current session',
    edit: 'Edit',
    general: 'General',
    instance: 'Instance',
    name: 'Name',
    of: 'of',
    command: 'Command',
    environmentVariables: 'Environment variables',
    volumes: 'Volumes',
    labels: 'Labels',
    rename: 'Rename',
    noData: 'No data',
    cpu: 'CPU',
    cpuCores: 'CPU Cores',
    memory: 'Memory',
    disk: 'Disk',
    loadAverage: 'Load',
    uptime: 'Uptime',
    platform: 'Platform',

    // Container states
    stateRunning: 'Running',
    stateExited: 'Exited',
    stateCreated: 'Created',
    statePaused: 'Paused',
    stateRestarting: 'Restarting',
    stateRemoving: 'Removing',
    stateDead: 'Dead',
    stateUnknown: 'Unknown',
    stateHealthy: 'Healthy',
    stateUp: 'Up',
    stateDown: 'Down',
    stateError: 'Error',
    stateWarning: 'Warning',
    stateStopped: 'Stopped',
    stateUnhealthy: 'Unhealthy',
    stateCrashLoopBackOff: 'CrashLoopBackOff',
    stateOOMKilled: 'OOMKilled',

    // Container detail panel
    containerDetails: 'Container Details',
    generalInfo: 'General Information',
    events: 'Events',
    logs: 'Logs',
    noEvents: 'No events',
    noLogs: 'No logs available',
    copyLogs: 'Copy logs',
    downloadLogs: 'Download logs',
    autoScroll: 'Auto scroll',
    showTimestamps: 'Show timestamps',
    refresh: 'Refresh',
    lines: 'lines',

    // Runtime navigation
    dockerContainers: 'Docker Containers',
    dockerImages: 'Docker Images',
    selectRuntime: 'Select a container technology',
    comingSoon: 'Coming soon',
    notAvailable: 'Not available yet',
    total: 'Total',
    allDockerContainers: 'All Docker containers in the cluster',
    registeredHosts: 'Hosts registered in the cluster',
    selectDevice: 'Select Device',
    chooseInstance: '-- Select a machine --',
    noDeviceSelectedTitle: 'No device selected',
    noDeviceSelectedDesc: 'Please select a machine or device from the menu above to view and manage its containers.',
    noContainersInInstance: 'No containers in this instance',
    containerNotFound: 'Container not found',
    instanceNotFound: 'Instance not found',
    hostMetrics: 'Host metrics',
    dockerImagesAvailable: 'Docker images available in the cluster',
    autoRemove: 'Auto-remove',
    removeContainer: 'Remove container',
    removeImage: 'Remove image',
    removeContainerConfirm: 'Do you want to remove the container "{name}"? This action cannot be undone.',
    removeImageConfirm: 'Do you want to delete the image "{name}"? This action cannot be undone.',
    errorRemovingContainer: 'Error removing the container',
    errorRemovingImage: 'Error removing the image',
    errorStartingContainer: 'Error starting the container',
    errorStoppingContainer: 'Error stopping the container',
    errorRestartingContainer: 'Error restarting the container',
    errorRenamingContainer: 'Error renaming the container',
    errorUpdatingImage: 'Error updating the image',
    errorDownloadingImage: 'Error downloading the image',
    selectContainerTechnology: 'Select a container technology',
    runtimeDescription: 'Manage {runtime} containers and images from your registered hosts.',
    dockerDescription: 'Manage Docker containers and images from your registered hosts.',
    podmanDescription: 'Rootless container and Podman image support coming soon.',
    rootless: 'rootless',

    // Auth
    welcomeBack: 'Welcome back',
    loginSubtitle: 'Sign in to continue to Orchestrack',
    email: 'Email',
    emailPlaceholder: 'you@email.com',
    passwordPlaceholder: '••••••••',
    confirmPassword: 'Confirm password',
    confirmPasswordPlaceholder: '••••••••',
    loggingIn: 'Signing in...',
    signingUp: 'Creating account...',
    login: 'Sign in',
    signUp: 'Sign up',
    createAccount: 'Create account',
    signupSubtitle: 'Sign up to get started with Orchestrack',
    noAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    passwordsDoNotMatch: 'Passwords do not match',
    statePending: 'Pending',
    addMachine: 'Add Machine',
    addDevice: 'Add Device',
    addDeviceDescription: 'Register a new device/agent in the Orchestrack network',
    approve: 'Approve',
    approving: 'Approving...',
    registrationToken: 'Registration Token',
    generateRegistrationToken: 'Generate Token',
    generatingToken: 'Generating...',
    runCommandOnDevice: "Run this command on the device's terminal:",
    copied: 'Copied',
    copy: 'Copy',
    close: 'Close',
    tokenExpiryNotice: 'This token will expire in 24 hours and can only be used once.',
    markAllAsRead: 'Mark all as read',
    noNotifications: 'No notifications',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot your password?',
    showPassword: 'Show password',
    hidePassword: 'Hide password',
    loginTagline: 'Manage your infrastructure from a single place.',
    loginDescription: 'Sign in to access your control panel and manage your devices.',
    orLoginWith: 'Or sign in with',
    forgotPasswordTitle: 'Recover password',
    forgotPasswordSubtitle: 'Enter your email and we will send you instructions to reset your password.',
    sendInstructions: 'Send instructions',
    sending: 'Sending...',
    backToLogin: 'Back to login',
    checkYourEmail: 'Check your email',
    resetEmailSent: 'If an account exists with that email, you will receive a link to reset your password.',
    passwordRequirements: 'Password must be at least 6 characters',
    signupTagline: 'Start monitoring your infrastructure today.',
    signupDescription: 'Create an account to access the control panel and manage your devices.',

    // Incidents and Root Cause Diagnostic
    incidents: 'Incidents',
    incidentDiagnostic: 'Incident Diagnostic',
    rootCause: 'Root Cause',
    rootCauseTrigger: 'Root Cause Trigger',
    origin: 'Origin',
    timeline: 'Timeline',
    incidentEvents: 'Incident Events',
    noIncidents: 'No incidents registered',
    incidentStatusOpen: 'Open',
    incidentStatusResolved: 'Resolved',
    propagation: 'Propagation',
    impact: 'Impact',
    eventSequence: 'Event Sequence',
    viewDiagnostic: 'View Diagnostic',
    closeDiagnostic: 'Close Diagnostic',
    inHost: 'in Host',
    incidentCreated: 'Incident created',
    incidentUpdated: 'Incident updated',
    incidentResolved: 'Incident resolved',
    noTimelineEvents: 'No events in the timeline',
    eventType: 'Event type',
    sequence: 'Sequence',

    // Fault propagation and Blast Radius (T-014)
    blastRadius: 'Blast Radius',
    affectedServers: 'Affected servers',
    affectedContainers: 'Affected containers',
    propagationDepth: 'Propagation depth',
    serversAffected: 'servers affected',
    containersAffected: 'containers affected',
    from: 'From',
    to: 'To',
    propagationMap: 'Propagation Map',
    noPropagationData: 'No propagation data',
    cascadeFailure: 'Cascade failure',
    impactSummary: 'Impact Summary',
    totalCluster: 'Total cluster',

    // Multi-host impact tree in real time (T-016)
    multiHostImpact: 'Multi-Host Impact Tree',
    livePropagation: 'Live Propagation',
    infrastructureAffected: 'Infrastructure affected',
    affectedHosts: 'Affected hosts',
    propagationInProgress: 'Propagation in progress',
    originServer: 'Origin server',
    noPropagationLive: 'No active propagation',

    // Affected Transactions and Services (T-021)
    affectedTransactionsAndServices: 'Affected Transactions and Services',
    noTransactionImpact: 'No affected transactions recorded for this incident',
    byCategory: 'By Category',
    byServer: 'By Server',
    failedRequests: 'failures',
    errors: 'errors',
    device: 'Device',
    noCategoryData: 'No category data',
    noServerTransactionData: 'No server transaction data',
    totalFailedRequests: 'Total failed requests',
    affectedCategories: 'Affected categories',

    // Container topology (T-026)
    containerTopology: 'Container Topology',
    containerNetworkGraph: 'Container Network Graph',
    noContainerTopology: 'No networked containers detected on this server',
    containersConnected: 'containers connected',
    networksDetected: 'networks detected',
    networkShared: 'Shared network',
    composeLink: 'Compose link',
    refreshTopology: 'Refresh topology',
    containerNetworkDescription: 'Containers joined by the same Docker network. The label shows the network and the link type between them.',
    servicesNetwork: 'Services network',

    // Multi-server topology map (T-017)
    topology: 'Topology',
    topologyMap: 'Topology Map',
    multiServerTopology: 'Multi-Server Topology',
    networkMap: 'Network Map',
    serverNodes: 'Server nodes',
    containerNodes: 'Container nodes',
    originNode: 'Origin node',
    propagationRoute: 'Propagation route',
    selectNode: 'Select a node',
    nodeMetrics: 'Node metrics',
    nodeContainers: 'Node containers',
    nodeEvents: 'Node events',
    connectedServers: 'Connected servers',
    clickNodeDetails: 'Click a node to view details',
    healthy: 'Healthy',
    degraded: 'Degraded',
    down: 'Down',
    backingEvidence: 'Backing Evidence',
    containerLogs: 'Container Logs',
    hostMetricsSnapshot: 'Metrics Snapshot',
    systemEventsDockerLogs: 'Docker Daemon Logs',
    exportForensicBundle: 'Export Forensic Bundle (ZIP)',
    waitingForEvidence: 'Waiting for evidence collection...',
    evidenceAvailable: 'Forensic evidence available for analysis.',
    noEvidenceAvailable: 'No evidence available for this incident.',
  },
}

interface LanguageContextValue {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('orchestrack-language')
    if (saved === 'es' || saved === 'en') return saved
    return 'es'
  })

  useEffect(() => {
    localStorage.setItem('orchestrack-language', language)
  }, [language])

  const setLanguage = (lang: Language) => setLanguageState(lang)

  const t = (key: string): string => {
    const value = translations[language][key]
    return typeof value === 'string' ? value : key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const ctx = useContext(LanguageContext)
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider')
  return ctx
}
