// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/docker/docker_container.proto

package docker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListContainersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Si es true, incluye contenedores detenidos.
	All bool `protobuf:"varint,1,opt,name=all,proto3" json:"all,omitempty"`
	// Filtros opcionales en formato clave=valor (por ejemplo: status=running).
	Filters       []*Label `protobuf:"bytes,2,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContainersRequest) Reset() {
	*x = ListContainersRequest{}
	mi := &file_proto_docker_docker_container_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContainersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContainersRequest) ProtoMessage() {}

func (x *ListContainersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_container_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContainersRequest.ProtoReflect.Descriptor instead.
func (*ListContainersRequest) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_container_proto_rawDescGZIP(), []int{0}
}

func (x *ListContainersRequest) GetAll() bool {
	if x != nil {
		return x.All
	}
	return false
}

func (x *ListContainersRequest) GetFilters() []*Label {
	if x != nil {
		return x.Filters
	}
	return nil
}

type ListContainersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Containers    []*ContainerSummary    `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContainersResponse) Reset() {
	*x = ListContainersResponse{}
	mi := &file_proto_docker_docker_container_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContainersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContainersResponse) ProtoMessage() {}

func (x *ListContainersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_container_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContainersResponse.ProtoReflect.Descriptor instead.
func (*ListContainersResponse) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_container_proto_rawDescGZIP(), []int{1}
}

func (x *ListContainersResponse) GetContainers() []*ContainerSummary {
	if x != nil {
		return x.Containers
	}
	return nil
}

type GetContainerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContainerRequest) Reset() {
	*x = GetContainerRequest{}
	mi := &file_proto_docker_docker_container_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContainerRequest) ProtoMessage() {}

func (x *GetContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_container_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContainerRequest.ProtoReflect.Descriptor instead.
func (*GetContainerRequest) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_container_proto_rawDescGZIP(), []int{2}
}

func (x *GetContainerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetContainerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Container     *Container             `protobuf:"bytes,1,opt,name=container,proto3" json:"container,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContainerResponse) Reset() {
	*x = GetContainerResponse{}
	mi := &file_proto_docker_docker_container_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContainerResponse) ProtoMessage() {}

func (x *GetContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_container_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContainerResponse.ProtoReflect.Descriptor instead.
func (*GetContainerResponse) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_container_proto_rawDescGZIP(), []int{3}
}

func (x *GetContainerResponse) GetContainer() *Container {
	if x != nil {
		return x.Container
	}
	return nil
}

type CreateContainerRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Image           string                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Command         string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	Args            []string               `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`
	Env             []*EnvVar              `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty"`
	ExposedPorts    []*Port                `protobuf:"bytes,6,rep,name=exposed_ports,json=exposedPorts,proto3" json:"exposed_ports,omitempty"`
	Volumes         []*VolumeMount         `protobuf:"bytes,7,rep,name=volumes,proto3" json:"volumes,omitempty"`
	Labels          []*Label               `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty"`
	Resources       *ContainerResources    `protobuf:"bytes,9,opt,name=resources,proto3" json:"resources,omitempty"`
	Tty             bool                   `protobuf:"varint,10,opt,name=tty,proto3" json:"tty,omitempty"`
	Interactive     bool                   `protobuf:"varint,11,opt,name=interactive,proto3" json:"interactive,omitempty"`
	AutoRemove      bool                   `protobuf:"varint,12,opt,name=auto_remove,json=autoRemove,proto3" json:"auto_remove,omitempty"`
	PublishAllPorts bool                   `protobuf:"varint,13,opt,name=publish_all_ports,json=publishAllPorts,proto3" json:"publish_all_ports,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateContainerRequest) Reset() {
	*x = CreateContainerRequest{}
	mi := &file_proto_docker_docker_container_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContainerRequest) ProtoMessage() {}

func (x *CreateContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_container_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContainerRequest.ProtoReflect.Descriptor instead.
func (*CreateContainerRequest) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_container_proto_rawDescGZIP(), []int{4}
}

func (x *CreateContainerRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *CreateContainerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateContainerRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CreateContainerRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *CreateContainerRequest) GetEnv() []*EnvVar {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *CreateContainerRequest) GetExposedPorts() []*Port {
	if x != nil {
		return x.ExposedPorts
	}
	return nil
}

func (x *CreateContainerRequest) GetVolumes() []*VolumeMount {
	if x != nil {
		return x.Volumes
	}
	return nil
}

func (x *CreateContainerRequest) GetLabels() []*Label {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *CreateContainerRequest) GetResources() *ContainerResources {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *CreateContainerRequest) GetTty() bool {
	if x != nil {
		return x.Tty
	}
	return false
}

func (x *CreateContainerRequest) GetInteractive() bool {
	if x != nil {
		return x.Interactive
	}
	return false
}

func (x *CreateContainerRequest) GetAutoRemove() bool {
	if x != nil {
		return x.AutoRemove
	}
	return false
}

func (x *CreateContainerRequest) GetPublishAllPorts() bool {
	if x != nil {
		return x.PublishAllPorts
	}
	return false
}

type CreateContainerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Warnings      []string               `protobuf:"bytes,3,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContainerResponse) Reset() {
	*x = CreateContainerResponse{}
	mi := &file_proto_docker_docker_container_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContainerResponse) ProtoMessage() {}

func (x *CreateContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_container_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContainerResponse.ProtoReflect.Descriptor instead.
func (*CreateContainerResponse) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_container_proto_rawDescGZIP(), []int{5}
}

func (x *CreateContainerResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateContainerResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateContainerResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

type StartContainerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartContainerRequest) Reset() {
	*x = StartContainerRequest{}
	mi := &file_proto_docker_docker_container_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartContainerRequest) ProtoMessage() {}

func (x *StartContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_container_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartContainerRequest.ProtoReflect.Descriptor instead.
func (*StartContainerRequest) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_container_proto_rawDescGZIP(), []int{6}
}

func (x *StartContainerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StartContainerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartContainerResponse) Reset() {
	*x = StartContainerResponse{}
	mi := &file_proto_docker_docker_container_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartContainerResponse) ProtoMessage() {}

func (x *StartContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_container_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartContainerResponse.ProtoReflect.Descriptor instead.
func (*StartContainerResponse) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_container_proto_rawDescGZIP(), []int{7}
}

func (x *StartContainerResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StopContainerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Tiempo de espera en segundos antes de forzar la detención.
	TimeoutSeconds int32 `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StopContainerRequest) Reset() {
	*x = StopContainerRequest{}
	mi := &file_proto_docker_docker_container_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopContainerRequest) ProtoMessage() {}

func (x *StopContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_container_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopContainerRequest.ProtoReflect.Descriptor instead.
func (*StopContainerRequest) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_container_proto_rawDescGZIP(), []int{8}
}

func (x *StopContainerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StopContainerRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type StopContainerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopContainerResponse) Reset() {
	*x = StopContainerResponse{}
	mi := &file_proto_docker_docker_container_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopContainerResponse) ProtoMessage() {}

func (x *StopContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_container_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopContainerResponse.ProtoReflect.Descriptor instead.
func (*StopContainerResponse) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_container_proto_rawDescGZIP(), []int{9}
}

func (x *StopContainerResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RestartContainerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Tiempo de espera en segundos antes de forzar la detención durante el reinicio.
	TimeoutSeconds int32 `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RestartContainerRequest) Reset() {
	*x = RestartContainerRequest{}
	mi := &file_proto_docker_docker_container_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartContainerRequest) ProtoMessage() {}

func (x *RestartContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_container_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartContainerRequest.ProtoReflect.Descriptor instead.
func (*RestartContainerRequest) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_container_proto_rawDescGZIP(), []int{10}
}

func (x *RestartContainerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RestartContainerRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type RestartContainerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartContainerResponse) Reset() {
	*x = RestartContainerResponse{}
	mi := &file_proto_docker_docker_container_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartContainerResponse) ProtoMessage() {}

func (x *RestartContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_container_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartContainerResponse.ProtoReflect.Descriptor instead.
func (*RestartContainerResponse) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_container_proto_rawDescGZIP(), []int{11}
}

func (x *RestartContainerResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RenameContainerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NewName       string                 `protobuf:"bytes,2,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameContainerRequest) Reset() {
	*x = RenameContainerRequest{}
	mi := &file_proto_docker_docker_container_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameContainerRequest) ProtoMessage() {}

func (x *RenameContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_container_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameContainerRequest.ProtoReflect.Descriptor instead.
func (*RenameContainerRequest) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_container_proto_rawDescGZIP(), []int{12}
}

func (x *RenameContainerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RenameContainerRequest) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

type RenameContainerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameContainerResponse) Reset() {
	*x = RenameContainerResponse{}
	mi := &file_proto_docker_docker_container_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameContainerResponse) ProtoMessage() {}

func (x *RenameContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_container_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameContainerResponse.ProtoReflect.Descriptor instead.
func (*RenameContainerResponse) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_container_proto_rawDescGZIP(), []int{13}
}

func (x *RenameContainerResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RenameContainerResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RemoveContainerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Si es true, fuerza la eliminación de un contenedor en ejecución.
	Force bool `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	// Si es true, elimina también los volúmenes asociados.
	RemoveVolumes bool `protobuf:"varint,3,opt,name=remove_volumes,json=removeVolumes,proto3" json:"remove_volumes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveContainerRequest) Reset() {
	*x = RemoveContainerRequest{}
	mi := &file_proto_docker_docker_container_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveContainerRequest) ProtoMessage() {}

func (x *RemoveContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_container_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveContainerRequest.ProtoReflect.Descriptor instead.
func (*RemoveContainerRequest) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_container_proto_rawDescGZIP(), []int{14}
}

func (x *RemoveContainerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RemoveContainerRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *RemoveContainerRequest) GetRemoveVolumes() bool {
	if x != nil {
		return x.RemoveVolumes
	}
	return false
}

type RemoveContainerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveContainerResponse) Reset() {
	*x = RemoveContainerResponse{}
	mi := &file_proto_docker_docker_container_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveContainerResponse) ProtoMessage() {}

func (x *RemoveContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_container_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveContainerResponse.ProtoReflect.Descriptor instead.
func (*RemoveContainerResponse) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_container_proto_rawDescGZIP(), []int{15}
}

func (x *RemoveContainerResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetContainerLogsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Número máximo de líneas a devolver desde el final (0 = todas).
	TailLines uint32 `protobuf:"varint,2,opt,name=tail_lines,json=tailLines,proto3" json:"tail_lines,omitempty"`
	// Si es true, prefija cada línea con su timestamp.
	Timestamps bool `protobuf:"varint,3,opt,name=timestamps,proto3" json:"timestamps,omitempty"`
	// Si es true, incluye el stream stdout.
	ShowStdout bool `protobuf:"varint,4,opt,name=show_stdout,json=showStdout,proto3" json:"show_stdout,omitempty"`
	// Si es true, incluye el stream stderr.
	ShowStderr    bool `protobuf:"varint,5,opt,name=show_stderr,json=showStderr,proto3" json:"show_stderr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContainerLogsRequest) Reset() {
	*x = GetContainerLogsRequest{}
	mi := &file_proto_docker_docker_container_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContainerLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContainerLogsRequest) ProtoMessage() {}

func (x *GetContainerLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_container_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContainerLogsRequest.ProtoReflect.Descriptor instead.
func (*GetContainerLogsRequest) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_container_proto_rawDescGZIP(), []int{16}
}

func (x *GetContainerLogsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetContainerLogsRequest) GetTailLines() uint32 {
	if x != nil {
		return x.TailLines
	}
	return 0
}

func (x *GetContainerLogsRequest) GetTimestamps() bool {
	if x != nil {
		return x.Timestamps
	}
	return false
}

func (x *GetContainerLogsRequest) GetShowStdout() bool {
	if x != nil {
		return x.ShowStdout
	}
	return false
}

func (x *GetContainerLogsRequest) GetShowStderr() bool {
	if x != nil {
		return x.ShowStderr
	}
	return false
}

type GetContainerLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lines         []string               `protobuf:"bytes,1,rep,name=lines,proto3" json:"lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContainerLogsResponse) Reset() {
	*x = GetContainerLogsResponse{}
	mi := &file_proto_docker_docker_container_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContainerLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContainerLogsResponse) ProtoMessage() {}

func (x *GetContainerLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_container_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContainerLogsResponse.ProtoReflect.Descriptor instead.
func (*GetContainerLogsResponse) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_container_proto_rawDescGZIP(), []int{17}
}

func (x *GetContainerLogsResponse) GetLines() []string {
	if x != nil {
		return x.Lines
	}
	return nil
}

type GetContainerTopologyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Reservado para filtros futuros.
	All           bool `protobuf:"varint,1,opt,name=all,proto3" json:"all,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContainerTopologyRequest) Reset() {
	*x = GetContainerTopologyRequest{}
	mi := &file_proto_docker_docker_container_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContainerTopologyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContainerTopologyRequest) ProtoMessage() {}

func (x *GetContainerTopologyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_container_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContainerTopologyRequest.ProtoReflect.Descriptor instead.
func (*GetContainerTopologyRequest) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_container_proto_rawDescGZIP(), []int{18}
}

func (x *GetContainerTopologyRequest) GetAll() bool {
	if x != nil {
		return x.All
	}
	return false
}

type GetContainerTopologyResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Links         []*ContainerNetworkLink `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContainerTopologyResponse) Reset() {
	*x = GetContainerTopologyResponse{}
	mi := &file_proto_docker_docker_container_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContainerTopologyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContainerTopologyResponse) ProtoMessage() {}

func (x *GetContainerTopologyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_container_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContainerTopologyResponse.ProtoReflect.Descriptor instead.
func (*GetContainerTopologyResponse) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_container_proto_rawDescGZIP(), []int{19}
}

func (x *GetContainerTopologyResponse) GetLinks() []*ContainerNetworkLink {
	if x != nil {
		return x.Links
	}
	return nil
}

type ContainerNetworkLink struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SourceContainerId   string                 `protobuf:"bytes,1,opt,name=source_container_id,json=sourceContainerId,proto3" json:"source_container_id,omitempty"`
	SourceContainerName string                 `protobuf:"bytes,2,opt,name=source_container_name,json=sourceContainerName,proto3" json:"source_container_name,omitempty"`
	TargetContainerId   string                 `protobuf:"bytes,3,opt,name=target_container_id,json=targetContainerId,proto3" json:"target_container_id,omitempty"`
	TargetContainerName string                 `protobuf:"bytes,4,opt,name=target_container_name,json=targetContainerName,proto3" json:"target_container_name,omitempty"`
	Network             string                 `protobuf:"bytes,5,opt,name=network,proto3" json:"network,omitempty"`
	Type                string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"` // network_shared, compose_link, port_exposed
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ContainerNetworkLink) Reset() {
	*x = ContainerNetworkLink{}
	mi := &file_proto_docker_docker_container_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerNetworkLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerNetworkLink) ProtoMessage() {}

func (x *ContainerNetworkLink) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_container_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerNetworkLink.ProtoReflect.Descriptor instead.
func (*ContainerNetworkLink) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_container_proto_rawDescGZIP(), []int{20}
}

func (x *ContainerNetworkLink) GetSourceContainerId() string {
	if x != nil {
		return x.SourceContainerId
	}
	return ""
}

func (x *ContainerNetworkLink) GetSourceContainerName() string {
	if x != nil {
		return x.SourceContainerName
	}
	return ""
}

func (x *ContainerNetworkLink) GetTargetContainerId() string {
	if x != nil {
		return x.TargetContainerId
	}
	return ""
}

func (x *ContainerNetworkLink) GetTargetContainerName() string {
	if x != nil {
		return x.TargetContainerName
	}
	return ""
}

func (x *ContainerNetworkLink) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *ContainerNetworkLink) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// Resumen de un contenedor para listados.
type ContainerSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Status        ContainerStatus        `protobuf:"varint,4,opt,name=status,proto3,enum=orchestrack.docker.ContainerStatus" json:"status,omitempty"`
	State         string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"` // Estado textual de Docker (running, exited, etc.)
	Ports         []*Port                `protobuf:"bytes,6,rep,name=ports,proto3" json:"ports,omitempty"`
	Created       int64                  `protobuf:"varint,7,opt,name=created,proto3" json:"created,omitempty"` // Timestamp en segundos
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerSummary) Reset() {
	*x = ContainerSummary{}
	mi := &file_proto_docker_docker_container_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerSummary) ProtoMessage() {}

func (x *ContainerSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_container_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerSummary.ProtoReflect.Descriptor instead.
func (*ContainerSummary) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_container_proto_rawDescGZIP(), []int{21}
}

func (x *ContainerSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContainerSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContainerSummary) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ContainerSummary) GetStatus() ContainerStatus {
	if x != nil {
		return x.Status
	}
	return ContainerStatus_CONTAINER_STATUS_UNSPECIFIED
}

func (x *ContainerSummary) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ContainerSummary) GetPorts() []*Port {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *ContainerSummary) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

// Detalle completo de un contenedor.
type Container struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Status        ContainerStatus        `protobuf:"varint,4,opt,name=status,proto3,enum=orchestrack.docker.ContainerStatus" json:"status,omitempty"`
	State         string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	Command       string                 `protobuf:"bytes,6,opt,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,7,rep,name=args,proto3" json:"args,omitempty"`
	Env           []*EnvVar              `protobuf:"bytes,8,rep,name=env,proto3" json:"env,omitempty"`
	Ports         []*Port                `protobuf:"bytes,9,rep,name=ports,proto3" json:"ports,omitempty"`
	Volumes       []*VolumeMount         `protobuf:"bytes,10,rep,name=volumes,proto3" json:"volumes,omitempty"`
	Labels        []*Label               `protobuf:"bytes,11,rep,name=labels,proto3" json:"labels,omitempty"`
	Resources     *ContainerResources    `protobuf:"bytes,12,opt,name=resources,proto3" json:"resources,omitempty"`
	Tty           bool                   `protobuf:"varint,13,opt,name=tty,proto3" json:"tty,omitempty"`
	Interactive   bool                   `protobuf:"varint,14,opt,name=interactive,proto3" json:"interactive,omitempty"`
	AutoRemove    bool                   `protobuf:"varint,15,opt,name=auto_remove,json=autoRemove,proto3" json:"auto_remove,omitempty"`
	Created       int64                  `protobuf:"varint,16,opt,name=created,proto3" json:"created,omitempty"`
	Platform      string                 `protobuf:"bytes,17,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Container) Reset() {
	*x = Container{}
	mi := &file_proto_docker_docker_container_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container) ProtoMessage() {}

func (x *Container) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_container_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container.ProtoReflect.Descriptor instead.
func (*Container) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_container_proto_rawDescGZIP(), []int{22}
}

func (x *Container) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Container) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Container) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Container) GetStatus() ContainerStatus {
	if x != nil {
		return x.Status
	}
	return ContainerStatus_CONTAINER_STATUS_UNSPECIFIED
}

func (x *Container) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Container) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Container) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *Container) GetEnv() []*EnvVar {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *Container) GetPorts() []*Port {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *Container) GetVolumes() []*VolumeMount {
	if x != nil {
		return x.Volumes
	}
	return nil
}

func (x *Container) GetLabels() []*Label {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Container) GetResources() *ContainerResources {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *Container) GetTty() bool {
	if x != nil {
		return x.Tty
	}
	return false
}

func (x *Container) GetInteractive() bool {
	if x != nil {
		return x.Interactive
	}
	return false
}

func (x *Container) GetAutoRemove() bool {
	if x != nil {
		return x.AutoRemove
	}
	return false
}

func (x *Container) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *Container) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

var File_proto_docker_docker_container_proto protoreflect.FileDescriptor

const file_proto_docker_docker_container_proto_rawDesc = "" +
	"\n" +
	"#proto/docker/docker_container.proto\x12\x12orchestrack.docker\x1a proto/docker/docker_common.proto\"^\n" +
	"\x15ListContainersRequest\x12\x10\n" +
	"\x03all\x18\x01 \x01(\bR\x03all\x123\n" +
	"\afilters\x18\x02 \x03(\v2\x19.orchestrack.docker.LabelR\afilters\"^\n" +
	"\x16ListContainersResponse\x12D\n" +
	"\n" +
	"containers\x18\x01 \x03(\v2$.orchestrack.docker.ContainerSummaryR\n" +
	"containers\"%\n" +
	"\x13GetContainerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"S\n" +
	"\x14GetContainerResponse\x12;\n" +
	"\tcontainer\x18\x01 \x01(\v2\x1d.orchestrack.docker.ContainerR\tcontainer\"\x92\x04\n" +
	"\x16CreateContainerRequest\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x04 \x03(\tR\x04args\x12,\n" +
	"\x03env\x18\x05 \x03(\v2\x1a.orchestrack.docker.EnvVarR\x03env\x12=\n" +
	"\rexposed_ports\x18\x06 \x03(\v2\x18.orchestrack.docker.PortR\fexposedPorts\x129\n" +
	"\avolumes\x18\a \x03(\v2\x1f.orchestrack.docker.VolumeMountR\avolumes\x121\n" +
	"\x06labels\x18\b \x03(\v2\x19.orchestrack.docker.LabelR\x06labels\x12D\n" +
	"\tresources\x18\t \x01(\v2&.orchestrack.docker.ContainerResourcesR\tresources\x12\x10\n" +
	"\x03tty\x18\n" +
	" \x01(\bR\x03tty\x12 \n" +
	"\vinteractive\x18\v \x01(\bR\vinteractive\x12\x1f\n" +
	"\vauto_remove\x18\f \x01(\bR\n" +
	"autoRemove\x12*\n" +
	"\x11publish_all_ports\x18\r \x01(\bR\x0fpublishAllPorts\"Y\n" +
	"\x17CreateContainerResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bwarnings\x18\x03 \x03(\tR\bwarnings\"'\n" +
	"\x15StartContainerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"(\n" +
	"\x16StartContainerResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"O\n" +
	"\x14StopContainerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0ftimeout_seconds\x18\x02 \x01(\x05R\x0etimeoutSeconds\"'\n" +
	"\x15StopContainerResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"R\n" +
	"\x17RestartContainerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0ftimeout_seconds\x18\x02 \x01(\x05R\x0etimeoutSeconds\"*\n" +
	"\x18RestartContainerResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"C\n" +
	"\x16RenameContainerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bnew_name\x18\x02 \x01(\tR\anewName\"=\n" +
	"\x17RenameContainerResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"e\n" +
	"\x16RemoveContainerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\x12%\n" +
	"\x0eremove_volumes\x18\x03 \x01(\bR\rremoveVolumes\")\n" +
	"\x17RemoveContainerResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xaa\x01\n" +
	"\x17GetContainerLogsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"tail_lines\x18\x02 \x01(\rR\ttailLines\x12\x1e\n" +
	"\n" +
	"timestamps\x18\x03 \x01(\bR\n" +
	"timestamps\x12\x1f\n" +
	"\vshow_stdout\x18\x04 \x01(\bR\n" +
	"showStdout\x12\x1f\n" +
	"\vshow_stderr\x18\x05 \x01(\bR\n" +
	"showStderr\"0\n" +
	"\x18GetContainerLogsResponse\x12\x14\n" +
	"\x05lines\x18\x01 \x03(\tR\x05lines\"/\n" +
	"\x1bGetContainerTopologyRequest\x12\x10\n" +
	"\x03all\x18\x01 \x01(\bR\x03all\"^\n" +
	"\x1cGetContainerTopologyResponse\x12>\n" +
	"\x05links\x18\x01 \x03(\v2(.orchestrack.docker.ContainerNetworkLinkR\x05links\"\x8c\x02\n" +
	"\x14ContainerNetworkLink\x12.\n" +
	"\x13source_container_id\x18\x01 \x01(\tR\x11sourceContainerId\x122\n" +
	"\x15source_container_name\x18\x02 \x01(\tR\x13sourceContainerName\x12.\n" +
	"\x13target_container_id\x18\x03 \x01(\tR\x11targetContainerId\x122\n" +
	"\x15target_container_name\x18\x04 \x01(\tR\x13targetContainerName\x12\x18\n" +
	"\anetwork\x18\x05 \x01(\tR\anetwork\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\"\xe9\x01\n" +
	"\x10ContainerSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12;\n" +
	"\x06status\x18\x04 \x01(\x0e2#.orchestrack.docker.ContainerStatusR\x06status\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12.\n" +
	"\x05ports\x18\x06 \x03(\v2\x18.orchestrack.docker.PortR\x05ports\x12\x18\n" +
	"\acreated\x18\a \x01(\x03R\acreated\"\xe3\x04\n" +
	"\tContainer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12;\n" +
	"\x06status\x18\x04 \x01(\x0e2#.orchestrack.docker.ContainerStatusR\x06status\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12\x18\n" +
	"\acommand\x18\x06 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\a \x03(\tR\x04args\x12,\n" +
	"\x03env\x18\b \x03(\v2\x1a.orchestrack.docker.EnvVarR\x03env\x12.\n" +
	"\x05ports\x18\t \x03(\v2\x18.orchestrack.docker.PortR\x05ports\x129\n" +
	"\avolumes\x18\n" +
	" \x03(\v2\x1f.orchestrack.docker.VolumeMountR\avolumes\x121\n" +
	"\x06labels\x18\v \x03(\v2\x19.orchestrack.docker.LabelR\x06labels\x12D\n" +
	"\tresources\x18\f \x01(\v2&.orchestrack.docker.ContainerResourcesR\tresources\x12\x10\n" +
	"\x03tty\x18\r \x01(\bR\x03tty\x12 \n" +
	"\vinteractive\x18\x0e \x01(\bR\vinteractive\x12\x1f\n" +
	"\vauto_remove\x18\x0f \x01(\bR\n" +
	"autoRemove\x12\x18\n" +
	"\acreated\x18\x10 \x01(\x03R\acreated\x12\x1a\n" +
	"\bplatform\x18\x11 \x01(\tR\bplatform2\xd5\a\n" +
	"\x16DockerContainerService\x12g\n" +
	"\x0eListContainers\x12).orchestrack.docker.ListContainersRequest\x1a*.orchestrack.docker.ListContainersResponse\x12a\n" +
	"\fGetContainer\x12'.orchestrack.docker.GetContainerRequest\x1a(.orchestrack.docker.GetContainerResponse\x12j\n" +
	"\x0fCreateContainer\x12*.orchestrack.docker.CreateContainerRequest\x1a+.orchestrack.docker.CreateContainerResponse\x12g\n" +
	"\x0eStartContainer\x12).orchestrack.docker.StartContainerRequest\x1a*.orchestrack.docker.StartContainerResponse\x12d\n" +
	"\rStopContainer\x12(.orchestrack.docker.StopContainerRequest\x1a).orchestrack.docker.StopContainerResponse\x12m\n" +
	"\x10RestartContainer\x12+.orchestrack.docker.RestartContainerRequest\x1a,.orchestrack.docker.RestartContainerResponse\x12j\n" +
	"\x0fRenameContainer\x12*.orchestrack.docker.RenameContainerRequest\x1a+.orchestrack.docker.RenameContainerResponse\x12j\n" +
	"\x0fRemoveContainer\x12*.orchestrack.docker.RemoveContainerRequest\x1a+.orchestrack.docker.RemoveContainerResponse\x12m\n" +
	"\x10GetContainerLogs\x12+.orchestrack.docker.GetContainerLogsRequest\x1a,.orchestrack.docker.GetContainerLogsResponseB7Z5github.com/go/orchestrack/backend/proto/docker;dockerb\x06proto3"

var (
	file_proto_docker_docker_container_proto_rawDescOnce sync.Once
	file_proto_docker_docker_container_proto_rawDescData []byte
)

func file_proto_docker_docker_container_proto_rawDescGZIP() []byte {
	file_proto_docker_docker_container_proto_rawDescOnce.Do(func() {
		file_proto_docker_docker_container_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_docker_docker_container_proto_rawDesc), len(file_proto_docker_docker_container_proto_rawDesc)))
	})
	return file_proto_docker_docker_container_proto_rawDescData
}

var file_proto_docker_docker_container_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_proto_docker_docker_container_proto_goTypes = []any{
	(*ListContainersRequest)(nil),        // 0: orchestrack.docker.ListContainersRequest
	(*ListContainersResponse)(nil),       // 1: orchestrack.docker.ListContainersResponse
	(*GetContainerRequest)(nil),          // 2: orchestrack.docker.GetContainerRequest
	(*GetContainerResponse)(nil),         // 3: orchestrack.docker.GetContainerResponse
	(*CreateContainerRequest)(nil),       // 4: orchestrack.docker.CreateContainerRequest
	(*CreateContainerResponse)(nil),      // 5: orchestrack.docker.CreateContainerResponse
	(*StartContainerRequest)(nil),        // 6: orchestrack.docker.StartContainerRequest
	(*StartContainerResponse)(nil),       // 7: orchestrack.docker.StartContainerResponse
	(*StopContainerRequest)(nil),         // 8: orchestrack.docker.StopContainerRequest
	(*StopContainerResponse)(nil),        // 9: orchestrack.docker.StopContainerResponse
	(*RestartContainerRequest)(nil),      // 10: orchestrack.docker.RestartContainerRequest
	(*RestartContainerResponse)(nil),     // 11: orchestrack.docker.RestartContainerResponse
	(*RenameContainerRequest)(nil),       // 12: orchestrack.docker.RenameContainerRequest
	(*RenameContainerResponse)(nil),      // 13: orchestrack.docker.RenameContainerResponse
	(*RemoveContainerRequest)(nil),       // 14: orchestrack.docker.RemoveContainerRequest
	(*RemoveContainerResponse)(nil),      // 15: orchestrack.docker.RemoveContainerResponse
	(*GetContainerLogsRequest)(nil),      // 16: orchestrack.docker.GetContainerLogsRequest
	(*GetContainerLogsResponse)(nil),     // 17: orchestrack.docker.GetContainerLogsResponse
	(*GetContainerTopologyRequest)(nil),  // 18: orchestrack.docker.GetContainerTopologyRequest
	(*GetContainerTopologyResponse)(nil), // 19: orchestrack.docker.GetContainerTopologyResponse
	(*ContainerNetworkLink)(nil),         // 20: orchestrack.docker.ContainerNetworkLink
	(*ContainerSummary)(nil),             // 21: orchestrack.docker.ContainerSummary
	(*Container)(nil),                    // 22: orchestrack.docker.Container
	(*Label)(nil),                        // 23: orchestrack.docker.Label
	(*EnvVar)(nil),                       // 24: orchestrack.docker.EnvVar
	(*Port)(nil),                         // 25: orchestrack.docker.Port
	(*VolumeMount)(nil),                  // 26: orchestrack.docker.VolumeMount
	(*ContainerResources)(nil),           // 27: orchestrack.docker.ContainerResources
	(ContainerStatus)(0),                 // 28: orchestrack.docker.ContainerStatus
}
var file_proto_docker_docker_container_proto_depIdxs = []int32{
	23, // 0: orchestrack.docker.ListContainersRequest.filters:type_name -> orchestrack.docker.Label
	21, // 1: orchestrack.docker.ListContainersResponse.containers:type_name -> orchestrack.docker.ContainerSummary
	22, // 2: orchestrack.docker.GetContainerResponse.container:type_name -> orchestrack.docker.Container
	24, // 3: orchestrack.docker.CreateContainerRequest.env:type_name -> orchestrack.docker.EnvVar
	25, // 4: orchestrack.docker.CreateContainerRequest.exposed_ports:type_name -> orchestrack.docker.Port
	26, // 5: orchestrack.docker.CreateContainerRequest.volumes:type_name -> orchestrack.docker.VolumeMount
	23, // 6: orchestrack.docker.CreateContainerRequest.labels:type_name -> orchestrack.docker.Label
	27, // 7: orchestrack.docker.CreateContainerRequest.resources:type_name -> orchestrack.docker.ContainerResources
	20, // 8: orchestrack.docker.GetContainerTopologyResponse.links:type_name -> orchestrack.docker.ContainerNetworkLink
	28, // 9: orchestrack.docker.ContainerSummary.status:type_name -> orchestrack.docker.ContainerStatus
	25, // 10: orchestrack.docker.ContainerSummary.ports:type_name -> orchestrack.docker.Port
	28, // 11: orchestrack.docker.Container.status:type_name -> orchestrack.docker.ContainerStatus
	24, // 12: orchestrack.docker.Container.env:type_name -> orchestrack.docker.EnvVar
	25, // 13: orchestrack.docker.Container.ports:type_name -> orchestrack.docker.Port
	26, // 14: orchestrack.docker.Container.volumes:type_name -> orchestrack.docker.VolumeMount
	23, // 15: orchestrack.docker.Container.labels:type_name -> orchestrack.docker.Label
	27, // 16: orchestrack.docker.Container.resources:type_name -> orchestrack.docker.ContainerResources
	0,  // 17: orchestrack.docker.DockerContainerService.ListContainers:input_type -> orchestrack.docker.ListContainersRequest
	2,  // 18: orchestrack.docker.DockerContainerService.GetContainer:input_type -> orchestrack.docker.GetContainerRequest
	4,  // 19: orchestrack.docker.DockerContainerService.CreateContainer:input_type -> orchestrack.docker.CreateContainerRequest
	6,  // 20: orchestrack.docker.DockerContainerService.StartContainer:input_type -> orchestrack.docker.StartContainerRequest
	8,  // 21: orchestrack.docker.DockerContainerService.StopContainer:input_type -> orchestrack.docker.StopContainerRequest
	10, // 22: orchestrack.docker.DockerContainerService.RestartContainer:input_type -> orchestrack.docker.RestartContainerRequest
	12, // 23: orchestrack.docker.DockerContainerService.RenameContainer:input_type -> orchestrack.docker.RenameContainerRequest
	14, // 24: orchestrack.docker.DockerContainerService.RemoveContainer:input_type -> orchestrack.docker.RemoveContainerRequest
	16, // 25: orchestrack.docker.DockerContainerService.GetContainerLogs:input_type -> orchestrack.docker.GetContainerLogsRequest
	1,  // 26: orchestrack.docker.DockerContainerService.ListContainers:output_type -> orchestrack.docker.ListContainersResponse
	3,  // 27: orchestrack.docker.DockerContainerService.GetContainer:output_type -> orchestrack.docker.GetContainerResponse
	5,  // 28: orchestrack.docker.DockerContainerService.CreateContainer:output_type -> orchestrack.docker.CreateContainerResponse
	7,  // 29: orchestrack.docker.DockerContainerService.StartContainer:output_type -> orchestrack.docker.StartContainerResponse
	9,  // 30: orchestrack.docker.DockerContainerService.StopContainer:output_type -> orchestrack.docker.StopContainerResponse
	11, // 31: orchestrack.docker.DockerContainerService.RestartContainer:output_type -> orchestrack.docker.RestartContainerResponse
	13, // 32: orchestrack.docker.DockerContainerService.RenameContainer:output_type -> orchestrack.docker.RenameContainerResponse
	15, // 33: orchestrack.docker.DockerContainerService.RemoveContainer:output_type -> orchestrack.docker.RemoveContainerResponse
	17, // 34: orchestrack.docker.DockerContainerService.GetContainerLogs:output_type -> orchestrack.docker.GetContainerLogsResponse
	26, // [26:35] is the sub-list for method output_type
	17, // [17:26] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_proto_docker_docker_container_proto_init() }
func file_proto_docker_docker_container_proto_init() {
	if File_proto_docker_docker_container_proto != nil {
		return
	}
	file_proto_docker_docker_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_docker_docker_container_proto_rawDesc), len(file_proto_docker_docker_container_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_docker_docker_container_proto_goTypes,
		DependencyIndexes: file_proto_docker_docker_container_proto_depIdxs,
		MessageInfos:      file_proto_docker_docker_container_proto_msgTypes,
	}.Build()
	File_proto_docker_docker_container_proto = out.File
	file_proto_docker_docker_container_proto_goTypes = nil
	file_proto_docker_docker_container_proto_depIdxs = nil
}
