// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/docker/docker_service.proto

package docker

import (
	system "github.com/go/orchestrack/backend/proto/system"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Información de registro/heartbeat de una instancia de docker-service.
type DockerServiceHeartbeat struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ServiceId string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Hostname  string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Status    string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // online, offline
	Timestamp int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Métricas del host asociado a esta instancia.
	HostMetrics   *system.HostMetrics `protobuf:"bytes,5,opt,name=host_metrics,json=hostMetrics,proto3" json:"host_metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DockerServiceHeartbeat) Reset() {
	*x = DockerServiceHeartbeat{}
	mi := &file_proto_docker_docker_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DockerServiceHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockerServiceHeartbeat) ProtoMessage() {}

func (x *DockerServiceHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockerServiceHeartbeat.ProtoReflect.Descriptor instead.
func (*DockerServiceHeartbeat) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_service_proto_rawDescGZIP(), []int{0}
}

func (x *DockerServiceHeartbeat) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *DockerServiceHeartbeat) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *DockerServiceHeartbeat) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DockerServiceHeartbeat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DockerServiceHeartbeat) GetHostMetrics() *system.HostMetrics {
	if x != nil {
		return x.HostMetrics
	}
	return nil
}

// Respuesta de un comando enviado por NATS request-reply.
type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"` // Mensaje protobuf serializado
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_proto_docker_docker_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_service_proto_rawDescGZIP(), []int{1}
}

func (x *CommandResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *CommandResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_proto_docker_docker_service_proto protoreflect.FileDescriptor

const file_proto_docker_docker_service_proto_rawDesc = "" +
	"\n" +
	"!proto/docker/docker_service.proto\x12\x12orchestrack.docker\x1a\x19proto/system/system.proto\"\xcd\x01\n" +
	"\x16DockerServiceHeartbeat\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12B\n" +
	"\fhost_metrics\x18\x05 \x01(\v2\x1f.orchestrack.system.HostMetricsR\vhostMetrics\"j\n" +
	"\x0fCommandResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayloadB7Z5github.com/go/orchestrack/backend/proto/docker;dockerb\x06proto3"

var (
	file_proto_docker_docker_service_proto_rawDescOnce sync.Once
	file_proto_docker_docker_service_proto_rawDescData []byte
)

func file_proto_docker_docker_service_proto_rawDescGZIP() []byte {
	file_proto_docker_docker_service_proto_rawDescOnce.Do(func() {
		file_proto_docker_docker_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_docker_docker_service_proto_rawDesc), len(file_proto_docker_docker_service_proto_rawDesc)))
	})
	return file_proto_docker_docker_service_proto_rawDescData
}

var file_proto_docker_docker_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_docker_docker_service_proto_goTypes = []any{
	(*DockerServiceHeartbeat)(nil), // 0: orchestrack.docker.DockerServiceHeartbeat
	(*CommandResponse)(nil),        // 1: orchestrack.docker.CommandResponse
	(*system.HostMetrics)(nil),     // 2: orchestrack.system.HostMetrics
}
var file_proto_docker_docker_service_proto_depIdxs = []int32{
	2, // 0: orchestrack.docker.DockerServiceHeartbeat.host_metrics:type_name -> orchestrack.system.HostMetrics
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_docker_docker_service_proto_init() }
func file_proto_docker_docker_service_proto_init() {
	if File_proto_docker_docker_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_docker_docker_service_proto_rawDesc), len(file_proto_docker_docker_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_docker_docker_service_proto_goTypes,
		DependencyIndexes: file_proto_docker_docker_service_proto_depIdxs,
		MessageInfos:      file_proto_docker_docker_service_proto_msgTypes,
	}.Build()
	File_proto_docker_docker_service_proto = out.File
	file_proto_docker_docker_service_proto_goTypes = nil
	file_proto_docker_docker_service_proto_depIdxs = nil
}
