// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/docker/docker_system.proto

package docker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Gestor de paquetes detectado en el host.
type PackageManager int32

const (
	PackageManager_PACKAGE_MANAGER_UNSPECIFIED PackageManager = 0
	PackageManager_PACKAGE_MANAGER_APT         PackageManager = 1 // Debian/Ubuntu
	PackageManager_PACKAGE_MANAGER_DNF         PackageManager = 2 // Fedora/RHEL 8+
	PackageManager_PACKAGE_MANAGER_YUM         PackageManager = 3 // RHEL/CentOS legacy
	PackageManager_PACKAGE_MANAGER_PACMAN      PackageManager = 4 // Arch/Manjaro
	PackageManager_PACKAGE_MANAGER_APK         PackageManager = 5 // Alpine
	PackageManager_PACKAGE_MANAGER_BREW        PackageManager = 6 // macOS
	PackageManager_PACKAGE_MANAGER_CHOCO       PackageManager = 7 // Windows
	PackageManager_PACKAGE_MANAGER_WINGET      PackageManager = 8 // Windows
)

// Enum value maps for PackageManager.
var (
	PackageManager_name = map[int32]string{
		0: "PACKAGE_MANAGER_UNSPECIFIED",
		1: "PACKAGE_MANAGER_APT",
		2: "PACKAGE_MANAGER_DNF",
		3: "PACKAGE_MANAGER_YUM",
		4: "PACKAGE_MANAGER_PACMAN",
		5: "PACKAGE_MANAGER_APK",
		6: "PACKAGE_MANAGER_BREW",
		7: "PACKAGE_MANAGER_CHOCO",
		8: "PACKAGE_MANAGER_WINGET",
	}
	PackageManager_value = map[string]int32{
		"PACKAGE_MANAGER_UNSPECIFIED": 0,
		"PACKAGE_MANAGER_APT":         1,
		"PACKAGE_MANAGER_DNF":         2,
		"PACKAGE_MANAGER_YUM":         3,
		"PACKAGE_MANAGER_PACMAN":      4,
		"PACKAGE_MANAGER_APK":         5,
		"PACKAGE_MANAGER_BREW":        6,
		"PACKAGE_MANAGER_CHOCO":       7,
		"PACKAGE_MANAGER_WINGET":      8,
	}
)

func (x PackageManager) Enum() *PackageManager {
	p := new(PackageManager)
	*p = x
	return p
}

func (x PackageManager) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PackageManager) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_docker_docker_system_proto_enumTypes[0].Descriptor()
}

func (PackageManager) Type() protoreflect.EnumType {
	return &file_proto_docker_docker_system_proto_enumTypes[0]
}

func (x PackageManager) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PackageManager.Descriptor instead.
func (PackageManager) EnumDescriptor() ([]byte, []int) {
	return file_proto_docker_docker_system_proto_rawDescGZIP(), []int{0}
}

// Información básica del sistema operativo.
type SystemInfo struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Os                    string                 `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`                                // linux, darwin, windows
	OsVersion             string                 `protobuf:"bytes,2,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"` // Versión del SO (ej. 22.04, 13.5)
	Architecture          string                 `protobuf:"bytes,3,opt,name=architecture,proto3" json:"architecture,omitempty"`            // amd64, arm64, etc.
	PackageManager        PackageManager         `protobuf:"varint,4,opt,name=package_manager,json=packageManager,proto3,enum=orchestrack.docker.PackageManager" json:"package_manager,omitempty"`
	PackageManagerVersion string                 `protobuf:"bytes,5,opt,name=package_manager_version,json=packageManagerVersion,proto3" json:"package_manager_version,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SystemInfo) Reset() {
	*x = SystemInfo{}
	mi := &file_proto_docker_docker_system_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfo) ProtoMessage() {}

func (x *SystemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_system_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfo.ProtoReflect.Descriptor instead.
func (*SystemInfo) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_system_proto_rawDescGZIP(), []int{0}
}

func (x *SystemInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *SystemInfo) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *SystemInfo) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *SystemInfo) GetPackageManager() PackageManager {
	if x != nil {
		return x.PackageManager
	}
	return PackageManager_PACKAGE_MANAGER_UNSPECIFIED
}

func (x *SystemInfo) GetPackageManagerVersion() string {
	if x != nil {
		return x.PackageManagerVersion
	}
	return ""
}

// Representación de un paquete del sistema.
type SystemPackage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Architecture  string                 `protobuf:"bytes,3,opt,name=architecture,proto3" json:"architecture,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`                                     // repositorio/origin (opcional)
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`                                     // installed, upgradable, etc.
	InstalledSize int64                  `protobuf:"varint,6,opt,name=installed_size,json=installedSize,proto3" json:"installed_size,omitempty"` // Tamaño instalado en bytes (0 si no aplica)
	Summary       string                 `protobuf:"bytes,7,opt,name=summary,proto3" json:"summary,omitempty"`                                   // Descripción corta (opcional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemPackage) Reset() {
	*x = SystemPackage{}
	mi := &file_proto_docker_docker_system_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemPackage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemPackage) ProtoMessage() {}

func (x *SystemPackage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_system_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemPackage.ProtoReflect.Descriptor instead.
func (*SystemPackage) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_system_proto_rawDescGZIP(), []int{1}
}

func (x *SystemPackage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SystemPackage) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *SystemPackage) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *SystemPackage) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *SystemPackage) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SystemPackage) GetInstalledSize() int64 {
	if x != nil {
		return x.InstalledSize
	}
	return 0
}

func (x *SystemPackage) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

type ListPackagesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filtro de búsqueda opcional por nombre.
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// Si es true, incluye paquetes que tienen actualización disponible.
	UpgradableOnly bool `protobuf:"varint,2,opt,name=upgradable_only,json=upgradableOnly,proto3" json:"upgradable_only,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListPackagesRequest) Reset() {
	*x = ListPackagesRequest{}
	mi := &file_proto_docker_docker_system_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPackagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPackagesRequest) ProtoMessage() {}

func (x *ListPackagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_system_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPackagesRequest.ProtoReflect.Descriptor instead.
func (*ListPackagesRequest) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_system_proto_rawDescGZIP(), []int{2}
}

func (x *ListPackagesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ListPackagesRequest) GetUpgradableOnly() bool {
	if x != nil {
		return x.UpgradableOnly
	}
	return false
}

type ListPackagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Packages      []*SystemPackage       `protobuf:"bytes,1,rep,name=packages,proto3" json:"packages,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPackagesResponse) Reset() {
	*x = ListPackagesResponse{}
	mi := &file_proto_docker_docker_system_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPackagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPackagesResponse) ProtoMessage() {}

func (x *ListPackagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_system_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPackagesResponse.ProtoReflect.Descriptor instead.
func (*ListPackagesResponse) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_system_proto_rawDescGZIP(), []int{3}
}

func (x *ListPackagesResponse) GetPackages() []*SystemPackage {
	if x != nil {
		return x.Packages
	}
	return nil
}

func (x *ListPackagesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type RefreshPackagesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Si es true, no ejecuta cambios, solo simula.
	DryRun        bool `protobuf:"varint,1,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshPackagesRequest) Reset() {
	*x = RefreshPackagesRequest{}
	mi := &file_proto_docker_docker_system_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshPackagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshPackagesRequest) ProtoMessage() {}

func (x *RefreshPackagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_system_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshPackagesRequest.ProtoReflect.Descriptor instead.
func (*RefreshPackagesRequest) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_system_proto_rawDescGZIP(), []int{4}
}

func (x *RefreshPackagesRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

type RefreshPackagesResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Output  string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	// Paquetes con actualización disponible detectada tras refrescar.
	UpgradablePackages []*SystemPackage `protobuf:"bytes,3,rep,name=upgradable_packages,json=upgradablePackages,proto3" json:"upgradable_packages,omitempty"`
	UpgradableCount    int32            `protobuf:"varint,4,opt,name=upgradable_count,json=upgradableCount,proto3" json:"upgradable_count,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RefreshPackagesResponse) Reset() {
	*x = RefreshPackagesResponse{}
	mi := &file_proto_docker_docker_system_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshPackagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshPackagesResponse) ProtoMessage() {}

func (x *RefreshPackagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_system_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshPackagesResponse.ProtoReflect.Descriptor instead.
func (*RefreshPackagesResponse) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_system_proto_rawDescGZIP(), []int{5}
}

func (x *RefreshPackagesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RefreshPackagesResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *RefreshPackagesResponse) GetUpgradablePackages() []*SystemPackage {
	if x != nil {
		return x.UpgradablePackages
	}
	return nil
}

func (x *RefreshPackagesResponse) GetUpgradableCount() int32 {
	if x != nil {
		return x.UpgradableCount
	}
	return 0
}

type UpgradePackagesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Si es true, no ejecuta cambios, solo simula.
	DryRun bool `protobuf:"varint,1,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	// Si es true, responde afirmativamente a las preguntas del gestor.
	AutoConfirm bool `protobuf:"varint,2,opt,name=auto_confirm,json=autoConfirm,proto3" json:"auto_confirm,omitempty"`
	// Lista de paquetes específicos; vacía = todos los disponibles.
	Packages      []string `protobuf:"bytes,3,rep,name=packages,proto3" json:"packages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpgradePackagesRequest) Reset() {
	*x = UpgradePackagesRequest{}
	mi := &file_proto_docker_docker_system_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradePackagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradePackagesRequest) ProtoMessage() {}

func (x *UpgradePackagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_system_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradePackagesRequest.ProtoReflect.Descriptor instead.
func (*UpgradePackagesRequest) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_system_proto_rawDescGZIP(), []int{6}
}

func (x *UpgradePackagesRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

func (x *UpgradePackagesRequest) GetAutoConfirm() bool {
	if x != nil {
		return x.AutoConfirm
	}
	return false
}

func (x *UpgradePackagesRequest) GetPackages() []string {
	if x != nil {
		return x.Packages
	}
	return nil
}

type UpgradePackagesResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Output         string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	UpgradedCount  int32                  `protobuf:"varint,3,opt,name=upgraded_count,json=upgradedCount,proto3" json:"upgraded_count,omitempty"`
	InstalledCount int32                  `protobuf:"varint,4,opt,name=installed_count,json=installedCount,proto3" json:"installed_count,omitempty"`
	RemovedCount   int32                  `protobuf:"varint,5,opt,name=removed_count,json=removedCount,proto3" json:"removed_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpgradePackagesResponse) Reset() {
	*x = UpgradePackagesResponse{}
	mi := &file_proto_docker_docker_system_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradePackagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradePackagesResponse) ProtoMessage() {}

func (x *UpgradePackagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_system_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradePackagesResponse.ProtoReflect.Descriptor instead.
func (*UpgradePackagesResponse) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_system_proto_rawDescGZIP(), []int{7}
}

func (x *UpgradePackagesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpgradePackagesResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *UpgradePackagesResponse) GetUpgradedCount() int32 {
	if x != nil {
		return x.UpgradedCount
	}
	return 0
}

func (x *UpgradePackagesResponse) GetInstalledCount() int32 {
	if x != nil {
		return x.InstalledCount
	}
	return 0
}

func (x *UpgradePackagesResponse) GetRemovedCount() int32 {
	if x != nil {
		return x.RemovedCount
	}
	return 0
}

type RemovePackagesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Lista de paquetes a eliminar.
	Packages []string `protobuf:"bytes,1,rep,name=packages,proto3" json:"packages,omitempty"`
	// Si es true, elimina también los archivos de configuración (APT purge, etc.).
	Purge bool `protobuf:"varint,2,opt,name=purge,proto3" json:"purge,omitempty"`
	// Si es true, responde afirmativamente a las preguntas del gestor.
	AutoConfirm bool `protobuf:"varint,3,opt,name=auto_confirm,json=autoConfirm,proto3" json:"auto_confirm,omitempty"`
	// Si es true, no ejecuta cambios, solo simula.
	DryRun        bool `protobuf:"varint,4,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePackagesRequest) Reset() {
	*x = RemovePackagesRequest{}
	mi := &file_proto_docker_docker_system_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePackagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePackagesRequest) ProtoMessage() {}

func (x *RemovePackagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_system_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePackagesRequest.ProtoReflect.Descriptor instead.
func (*RemovePackagesRequest) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_system_proto_rawDescGZIP(), []int{8}
}

func (x *RemovePackagesRequest) GetPackages() []string {
	if x != nil {
		return x.Packages
	}
	return nil
}

func (x *RemovePackagesRequest) GetPurge() bool {
	if x != nil {
		return x.Purge
	}
	return false
}

func (x *RemovePackagesRequest) GetAutoConfirm() bool {
	if x != nil {
		return x.AutoConfirm
	}
	return false
}

func (x *RemovePackagesRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

type RemovePackagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	RemovedCount  int32                  `protobuf:"varint,3,opt,name=removed_count,json=removedCount,proto3" json:"removed_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePackagesResponse) Reset() {
	*x = RemovePackagesResponse{}
	mi := &file_proto_docker_docker_system_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePackagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePackagesResponse) ProtoMessage() {}

func (x *RemovePackagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_system_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePackagesResponse.ProtoReflect.Descriptor instead.
func (*RemovePackagesResponse) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_system_proto_rawDescGZIP(), []int{9}
}

func (x *RemovePackagesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemovePackagesResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *RemovePackagesResponse) GetRemovedCount() int32 {
	if x != nil {
		return x.RemovedCount
	}
	return 0
}

type GetSystemInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemInfoRequest) Reset() {
	*x = GetSystemInfoRequest{}
	mi := &file_proto_docker_docker_system_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemInfoRequest) ProtoMessage() {}

func (x *GetSystemInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_system_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemInfoRequest.ProtoReflect.Descriptor instead.
func (*GetSystemInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_system_proto_rawDescGZIP(), []int{10}
}

type GetSystemInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *SystemInfo            `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemInfoResponse) Reset() {
	*x = GetSystemInfoResponse{}
	mi := &file_proto_docker_docker_system_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemInfoResponse) ProtoMessage() {}

func (x *GetSystemInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_system_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemInfoResponse.ProtoReflect.Descriptor instead.
func (*GetSystemInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_system_proto_rawDescGZIP(), []int{11}
}

func (x *GetSystemInfoResponse) GetInfo() *SystemInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

var File_proto_docker_docker_system_proto protoreflect.FileDescriptor

const file_proto_docker_docker_system_proto_rawDesc = "" +
	"\n" +
	" proto/docker/docker_system.proto\x12\x12orchestrack.docker\"\xe4\x01\n" +
	"\n" +
	"SystemInfo\x12\x0e\n" +
	"\x02os\x18\x01 \x01(\tR\x02os\x12\x1d\n" +
	"\n" +
	"os_version\x18\x02 \x01(\tR\tosVersion\x12\"\n" +
	"\farchitecture\x18\x03 \x01(\tR\farchitecture\x12K\n" +
	"\x0fpackage_manager\x18\x04 \x01(\x0e2\".orchestrack.docker.PackageManagerR\x0epackageManager\x126\n" +
	"\x17package_manager_version\x18\x05 \x01(\tR\x15packageManagerVersion\"\xd2\x01\n" +
	"\rSystemPackage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\"\n" +
	"\farchitecture\x18\x03 \x01(\tR\farchitecture\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12%\n" +
	"\x0einstalled_size\x18\x06 \x01(\x03R\rinstalledSize\x12\x18\n" +
	"\asummary\x18\a \x01(\tR\asummary\"T\n" +
	"\x13ListPackagesRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12'\n" +
	"\x0fupgradable_only\x18\x02 \x01(\bR\x0eupgradableOnly\"k\n" +
	"\x14ListPackagesResponse\x12=\n" +
	"\bpackages\x18\x01 \x03(\v2!.orchestrack.docker.SystemPackageR\bpackages\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"1\n" +
	"\x16RefreshPackagesRequest\x12\x17\n" +
	"\adry_run\x18\x01 \x01(\bR\x06dryRun\"\xca\x01\n" +
	"\x17RefreshPackagesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12R\n" +
	"\x13upgradable_packages\x18\x03 \x03(\v2!.orchestrack.docker.SystemPackageR\x12upgradablePackages\x12)\n" +
	"\x10upgradable_count\x18\x04 \x01(\x05R\x0fupgradableCount\"p\n" +
	"\x16UpgradePackagesRequest\x12\x17\n" +
	"\adry_run\x18\x01 \x01(\bR\x06dryRun\x12!\n" +
	"\fauto_confirm\x18\x02 \x01(\bR\vautoConfirm\x12\x1a\n" +
	"\bpackages\x18\x03 \x03(\tR\bpackages\"\xc0\x01\n" +
	"\x17UpgradePackagesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12%\n" +
	"\x0eupgraded_count\x18\x03 \x01(\x05R\rupgradedCount\x12'\n" +
	"\x0finstalled_count\x18\x04 \x01(\x05R\x0einstalledCount\x12#\n" +
	"\rremoved_count\x18\x05 \x01(\x05R\fremovedCount\"\x85\x01\n" +
	"\x15RemovePackagesRequest\x12\x1a\n" +
	"\bpackages\x18\x01 \x03(\tR\bpackages\x12\x14\n" +
	"\x05purge\x18\x02 \x01(\bR\x05purge\x12!\n" +
	"\fauto_confirm\x18\x03 \x01(\bR\vautoConfirm\x12\x17\n" +
	"\adry_run\x18\x04 \x01(\bR\x06dryRun\"o\n" +
	"\x16RemovePackagesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12#\n" +
	"\rremoved_count\x18\x03 \x01(\x05R\fremovedCount\"\x16\n" +
	"\x14GetSystemInfoRequest\"K\n" +
	"\x15GetSystemInfoResponse\x122\n" +
	"\x04info\x18\x01 \x01(\v2\x1e.orchestrack.docker.SystemInfoR\x04info*\x82\x02\n" +
	"\x0ePackageManager\x12\x1f\n" +
	"\x1bPACKAGE_MANAGER_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13PACKAGE_MANAGER_APT\x10\x01\x12\x17\n" +
	"\x13PACKAGE_MANAGER_DNF\x10\x02\x12\x17\n" +
	"\x13PACKAGE_MANAGER_YUM\x10\x03\x12\x1a\n" +
	"\x16PACKAGE_MANAGER_PACMAN\x10\x04\x12\x17\n" +
	"\x13PACKAGE_MANAGER_APK\x10\x05\x12\x18\n" +
	"\x14PACKAGE_MANAGER_BREW\x10\x06\x12\x19\n" +
	"\x15PACKAGE_MANAGER_CHOCO\x10\a\x12\x1a\n" +
	"\x16PACKAGE_MANAGER_WINGET\x10\bB7Z5github.com/go/orchestrack/backend/proto/docker;dockerb\x06proto3"

var (
	file_proto_docker_docker_system_proto_rawDescOnce sync.Once
	file_proto_docker_docker_system_proto_rawDescData []byte
)

func file_proto_docker_docker_system_proto_rawDescGZIP() []byte {
	file_proto_docker_docker_system_proto_rawDescOnce.Do(func() {
		file_proto_docker_docker_system_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_docker_docker_system_proto_rawDesc), len(file_proto_docker_docker_system_proto_rawDesc)))
	})
	return file_proto_docker_docker_system_proto_rawDescData
}

var file_proto_docker_docker_system_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_docker_docker_system_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_docker_docker_system_proto_goTypes = []any{
	(PackageManager)(0),             // 0: orchestrack.docker.PackageManager
	(*SystemInfo)(nil),              // 1: orchestrack.docker.SystemInfo
	(*SystemPackage)(nil),           // 2: orchestrack.docker.SystemPackage
	(*ListPackagesRequest)(nil),     // 3: orchestrack.docker.ListPackagesRequest
	(*ListPackagesResponse)(nil),    // 4: orchestrack.docker.ListPackagesResponse
	(*RefreshPackagesRequest)(nil),  // 5: orchestrack.docker.RefreshPackagesRequest
	(*RefreshPackagesResponse)(nil), // 6: orchestrack.docker.RefreshPackagesResponse
	(*UpgradePackagesRequest)(nil),  // 7: orchestrack.docker.UpgradePackagesRequest
	(*UpgradePackagesResponse)(nil), // 8: orchestrack.docker.UpgradePackagesResponse
	(*RemovePackagesRequest)(nil),   // 9: orchestrack.docker.RemovePackagesRequest
	(*RemovePackagesResponse)(nil),  // 10: orchestrack.docker.RemovePackagesResponse
	(*GetSystemInfoRequest)(nil),    // 11: orchestrack.docker.GetSystemInfoRequest
	(*GetSystemInfoResponse)(nil),   // 12: orchestrack.docker.GetSystemInfoResponse
}
var file_proto_docker_docker_system_proto_depIdxs = []int32{
	0, // 0: orchestrack.docker.SystemInfo.package_manager:type_name -> orchestrack.docker.PackageManager
	2, // 1: orchestrack.docker.ListPackagesResponse.packages:type_name -> orchestrack.docker.SystemPackage
	2, // 2: orchestrack.docker.RefreshPackagesResponse.upgradable_packages:type_name -> orchestrack.docker.SystemPackage
	1, // 3: orchestrack.docker.GetSystemInfoResponse.info:type_name -> orchestrack.docker.SystemInfo
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_docker_docker_system_proto_init() }
func file_proto_docker_docker_system_proto_init() {
	if File_proto_docker_docker_system_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_docker_docker_system_proto_rawDesc), len(file_proto_docker_docker_system_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_docker_docker_system_proto_goTypes,
		DependencyIndexes: file_proto_docker_docker_system_proto_depIdxs,
		EnumInfos:         file_proto_docker_docker_system_proto_enumTypes,
		MessageInfos:      file_proto_docker_docker_system_proto_msgTypes,
	}.Build()
	File_proto_docker_docker_system_proto = out.File
	file_proto_docker_docker_system_proto_goTypes = nil
	file_proto_docker_docker_system_proto_depIdxs = nil
}
