// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/docker/docker_service.proto

package docker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Métricas del host/servidor donde corre docker-service.
type HostMetrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Uso de CPU en porcentaje (0-100).
	CpuPercent float64 `protobuf:"fixed64,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	// Memoria total en bytes.
	MemoryTotal int64 `protobuf:"varint,2,opt,name=memory_total,json=memoryTotal,proto3" json:"memory_total,omitempty"`
	// Memoria usada en bytes.
	MemoryUsed int64 `protobuf:"varint,3,opt,name=memory_used,json=memoryUsed,proto3" json:"memory_used,omitempty"`
	// Porcentaje de memoria usada (0-100).
	MemoryPercent float64 `protobuf:"fixed64,4,opt,name=memory_percent,json=memoryPercent,proto3" json:"memory_percent,omitempty"`
	// Espacio en disco total en bytes.
	DiskTotal int64 `protobuf:"varint,5,opt,name=disk_total,json=diskTotal,proto3" json:"disk_total,omitempty"`
	// Espacio en disco usado en bytes.
	DiskUsed int64 `protobuf:"varint,6,opt,name=disk_used,json=diskUsed,proto3" json:"disk_used,omitempty"`
	// Porcentaje de disco usado (0-100).
	DiskPercent float64 `protobuf:"fixed64,7,opt,name=disk_percent,json=diskPercent,proto3" json:"disk_percent,omitempty"`
	// Carga promedio del sistema (1 min).
	LoadAverage float64 `protobuf:"fixed64,8,opt,name=load_average,json=loadAverage,proto3" json:"load_average,omitempty"`
	// Tiempo de actividad del servidor en segundos.
	UptimeSeconds int64 `protobuf:"varint,9,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	// Número de núcleos de CPU.
	CpuCores int32 `protobuf:"varint,10,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	// Nombre de la plataforma/sistema operativo.
	Platform string `protobuf:"bytes,11,opt,name=platform,proto3" json:"platform,omitempty"`
	// Procesos principales del sistema ordenados por uso de CPU.
	Processes []*ProcessInfo `protobuf:"bytes,12,rep,name=processes,proto3" json:"processes,omitempty"`
	// Número total de procesos en ejecución en el host.
	ProcessCount  int32 `protobuf:"varint,13,opt,name=process_count,json=processCount,proto3" json:"process_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostMetrics) Reset() {
	*x = HostMetrics{}
	mi := &file_proto_docker_docker_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostMetrics) ProtoMessage() {}

func (x *HostMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostMetrics.ProtoReflect.Descriptor instead.
func (*HostMetrics) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_service_proto_rawDescGZIP(), []int{0}
}

func (x *HostMetrics) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *HostMetrics) GetMemoryTotal() int64 {
	if x != nil {
		return x.MemoryTotal
	}
	return 0
}

func (x *HostMetrics) GetMemoryUsed() int64 {
	if x != nil {
		return x.MemoryUsed
	}
	return 0
}

func (x *HostMetrics) GetMemoryPercent() float64 {
	if x != nil {
		return x.MemoryPercent
	}
	return 0
}

func (x *HostMetrics) GetDiskTotal() int64 {
	if x != nil {
		return x.DiskTotal
	}
	return 0
}

func (x *HostMetrics) GetDiskUsed() int64 {
	if x != nil {
		return x.DiskUsed
	}
	return 0
}

func (x *HostMetrics) GetDiskPercent() float64 {
	if x != nil {
		return x.DiskPercent
	}
	return 0
}

func (x *HostMetrics) GetLoadAverage() float64 {
	if x != nil {
		return x.LoadAverage
	}
	return 0
}

func (x *HostMetrics) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *HostMetrics) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *HostMetrics) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *HostMetrics) GetProcesses() []*ProcessInfo {
	if x != nil {
		return x.Processes
	}
	return nil
}

func (x *HostMetrics) GetProcessCount() int32 {
	if x != nil {
		return x.ProcessCount
	}
	return 0
}

// Información de un proceso del sistema operativo.
type ProcessInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PID del proceso.
	Pid int32 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	// Nombre del ejecutable.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Porcentaje de uso de CPU (0-100).
	CpuPercent float64 `protobuf:"fixed64,3,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	// Porcentaje de uso de memoria (0-100).
	MemoryPercent float64 `protobuf:"fixed64,4,opt,name=memory_percent,json=memoryPercent,proto3" json:"memory_percent,omitempty"`
	// Memoria usada por el proceso en bytes.
	MemoryBytes   int64 `protobuf:"varint,5,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessInfo) Reset() {
	*x = ProcessInfo{}
	mi := &file_proto_docker_docker_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInfo) ProtoMessage() {}

func (x *ProcessInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInfo.ProtoReflect.Descriptor instead.
func (*ProcessInfo) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_service_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessInfo) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessInfo) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ProcessInfo) GetMemoryPercent() float64 {
	if x != nil {
		return x.MemoryPercent
	}
	return 0
}

func (x *ProcessInfo) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

// Información de registro/heartbeat de una instancia de docker-service.
type DockerServiceHeartbeat struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ServiceId string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Hostname  string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Status    string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // online, offline
	Timestamp int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Métricas del host asociado a esta instancia.
	HostMetrics   *HostMetrics `protobuf:"bytes,5,opt,name=host_metrics,json=hostMetrics,proto3" json:"host_metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DockerServiceHeartbeat) Reset() {
	*x = DockerServiceHeartbeat{}
	mi := &file_proto_docker_docker_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DockerServiceHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockerServiceHeartbeat) ProtoMessage() {}

func (x *DockerServiceHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockerServiceHeartbeat.ProtoReflect.Descriptor instead.
func (*DockerServiceHeartbeat) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_service_proto_rawDescGZIP(), []int{2}
}

func (x *DockerServiceHeartbeat) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *DockerServiceHeartbeat) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *DockerServiceHeartbeat) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DockerServiceHeartbeat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DockerServiceHeartbeat) GetHostMetrics() *HostMetrics {
	if x != nil {
		return x.HostMetrics
	}
	return nil
}

// Respuesta de un comando enviado por NATS request-reply.
type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"` // Mensaje protobuf serializado
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_proto_docker_docker_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_service_proto_rawDescGZIP(), []int{3}
}

func (x *CommandResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *CommandResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SearchProcessesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filtro por nombre del proceso (case-insensitive, substring).
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// Si es true, busca también por PID exacto.
	SearchByPid bool `protobuf:"varint,2,opt,name=search_by_pid,json=searchByPid,proto3" json:"search_by_pid,omitempty"`
	// Número máximo de resultados (por defecto 20).
	Limit         int32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchProcessesRequest) Reset() {
	*x = SearchProcessesRequest{}
	mi := &file_proto_docker_docker_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchProcessesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchProcessesRequest) ProtoMessage() {}

func (x *SearchProcessesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchProcessesRequest.ProtoReflect.Descriptor instead.
func (*SearchProcessesRequest) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_service_proto_rawDescGZIP(), []int{4}
}

func (x *SearchProcessesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchProcessesRequest) GetSearchByPid() bool {
	if x != nil {
		return x.SearchByPid
	}
	return false
}

func (x *SearchProcessesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchProcessesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Processes     []*ProcessInfo         `protobuf:"bytes,1,rep,name=processes,proto3" json:"processes,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchProcessesResponse) Reset() {
	*x = SearchProcessesResponse{}
	mi := &file_proto_docker_docker_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchProcessesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchProcessesResponse) ProtoMessage() {}

func (x *SearchProcessesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchProcessesResponse.ProtoReflect.Descriptor instead.
func (*SearchProcessesResponse) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_service_proto_rawDescGZIP(), []int{5}
}

func (x *SearchProcessesResponse) GetProcesses() []*ProcessInfo {
	if x != nil {
		return x.Processes
	}
	return nil
}

func (x *SearchProcessesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_proto_docker_docker_service_proto protoreflect.FileDescriptor

const file_proto_docker_docker_service_proto_rawDesc = "" +
	"\n" +
	"!proto/docker/docker_service.proto\x12\x12orchestrack.docker\"\xdf\x03\n" +
	"\vHostMetrics\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x01R\n" +
	"cpuPercent\x12!\n" +
	"\fmemory_total\x18\x02 \x01(\x03R\vmemoryTotal\x12\x1f\n" +
	"\vmemory_used\x18\x03 \x01(\x03R\n" +
	"memoryUsed\x12%\n" +
	"\x0ememory_percent\x18\x04 \x01(\x01R\rmemoryPercent\x12\x1d\n" +
	"\n" +
	"disk_total\x18\x05 \x01(\x03R\tdiskTotal\x12\x1b\n" +
	"\tdisk_used\x18\x06 \x01(\x03R\bdiskUsed\x12!\n" +
	"\fdisk_percent\x18\a \x01(\x01R\vdiskPercent\x12!\n" +
	"\fload_average\x18\b \x01(\x01R\vloadAverage\x12%\n" +
	"\x0euptime_seconds\x18\t \x01(\x03R\ruptimeSeconds\x12\x1b\n" +
	"\tcpu_cores\x18\n" +
	" \x01(\x05R\bcpuCores\x12\x1a\n" +
	"\bplatform\x18\v \x01(\tR\bplatform\x12=\n" +
	"\tprocesses\x18\f \x03(\v2\x1f.orchestrack.docker.ProcessInfoR\tprocesses\x12#\n" +
	"\rprocess_count\x18\r \x01(\x05R\fprocessCount\"\x9e\x01\n" +
	"\vProcessInfo\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vcpu_percent\x18\x03 \x01(\x01R\n" +
	"cpuPercent\x12%\n" +
	"\x0ememory_percent\x18\x04 \x01(\x01R\rmemoryPercent\x12!\n" +
	"\fmemory_bytes\x18\x05 \x01(\x03R\vmemoryBytes\"\xcd\x01\n" +
	"\x16DockerServiceHeartbeat\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12B\n" +
	"\fhost_metrics\x18\x05 \x01(\v2\x1f.orchestrack.docker.HostMetricsR\vhostMetrics\"j\n" +
	"\x0fCommandResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"h\n" +
	"\x16SearchProcessesRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\"\n" +
	"\rsearch_by_pid\x18\x02 \x01(\bR\vsearchByPid\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"n\n" +
	"\x17SearchProcessesResponse\x12=\n" +
	"\tprocesses\x18\x01 \x03(\v2\x1f.orchestrack.docker.ProcessInfoR\tprocesses\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05totalB7Z5github.com/go/orchestrack/backend/proto/docker;dockerb\x06proto3"

var (
	file_proto_docker_docker_service_proto_rawDescOnce sync.Once
	file_proto_docker_docker_service_proto_rawDescData []byte
)

func file_proto_docker_docker_service_proto_rawDescGZIP() []byte {
	file_proto_docker_docker_service_proto_rawDescOnce.Do(func() {
		file_proto_docker_docker_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_docker_docker_service_proto_rawDesc), len(file_proto_docker_docker_service_proto_rawDesc)))
	})
	return file_proto_docker_docker_service_proto_rawDescData
}

var file_proto_docker_docker_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_docker_docker_service_proto_goTypes = []any{
	(*HostMetrics)(nil),             // 0: orchestrack.docker.HostMetrics
	(*ProcessInfo)(nil),             // 1: orchestrack.docker.ProcessInfo
	(*DockerServiceHeartbeat)(nil),  // 2: orchestrack.docker.DockerServiceHeartbeat
	(*CommandResponse)(nil),         // 3: orchestrack.docker.CommandResponse
	(*SearchProcessesRequest)(nil),  // 4: orchestrack.docker.SearchProcessesRequest
	(*SearchProcessesResponse)(nil), // 5: orchestrack.docker.SearchProcessesResponse
}
var file_proto_docker_docker_service_proto_depIdxs = []int32{
	1, // 0: orchestrack.docker.HostMetrics.processes:type_name -> orchestrack.docker.ProcessInfo
	0, // 1: orchestrack.docker.DockerServiceHeartbeat.host_metrics:type_name -> orchestrack.docker.HostMetrics
	1, // 2: orchestrack.docker.SearchProcessesResponse.processes:type_name -> orchestrack.docker.ProcessInfo
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_docker_docker_service_proto_init() }
func file_proto_docker_docker_service_proto_init() {
	if File_proto_docker_docker_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_docker_docker_service_proto_rawDesc), len(file_proto_docker_docker_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_docker_docker_service_proto_goTypes,
		DependencyIndexes: file_proto_docker_docker_service_proto_depIdxs,
		MessageInfos:      file_proto_docker_docker_service_proto_msgTypes,
	}.Build()
	File_proto_docker_docker_service_proto = out.File
	file_proto_docker_docker_service_proto_goTypes = nil
	file_proto_docker_docker_service_proto_depIdxs = nil
}
