// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/docker/docker_common.proto

package docker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Estados posibles de un contenedor según Docker.
type ContainerStatus int32

const (
	ContainerStatus_CONTAINER_STATUS_UNSPECIFIED ContainerStatus = 0
	ContainerStatus_CONTAINER_STATUS_CREATED     ContainerStatus = 1
	ContainerStatus_CONTAINER_STATUS_RUNNING     ContainerStatus = 2
	ContainerStatus_CONTAINER_STATUS_PAUSED      ContainerStatus = 3
	ContainerStatus_CONTAINER_STATUS_RESTARTING  ContainerStatus = 4
	ContainerStatus_CONTAINER_STATUS_REMOVING    ContainerStatus = 5
	ContainerStatus_CONTAINER_STATUS_EXITED      ContainerStatus = 6
	ContainerStatus_CONTAINER_STATUS_DEAD        ContainerStatus = 7
)

// Enum value maps for ContainerStatus.
var (
	ContainerStatus_name = map[int32]string{
		0: "CONTAINER_STATUS_UNSPECIFIED",
		1: "CONTAINER_STATUS_CREATED",
		2: "CONTAINER_STATUS_RUNNING",
		3: "CONTAINER_STATUS_PAUSED",
		4: "CONTAINER_STATUS_RESTARTING",
		5: "CONTAINER_STATUS_REMOVING",
		6: "CONTAINER_STATUS_EXITED",
		7: "CONTAINER_STATUS_DEAD",
	}
	ContainerStatus_value = map[string]int32{
		"CONTAINER_STATUS_UNSPECIFIED": 0,
		"CONTAINER_STATUS_CREATED":     1,
		"CONTAINER_STATUS_RUNNING":     2,
		"CONTAINER_STATUS_PAUSED":      3,
		"CONTAINER_STATUS_RESTARTING":  4,
		"CONTAINER_STATUS_REMOVING":    5,
		"CONTAINER_STATUS_EXITED":      6,
		"CONTAINER_STATUS_DEAD":        7,
	}
)

func (x ContainerStatus) Enum() *ContainerStatus {
	p := new(ContainerStatus)
	*p = x
	return p
}

func (x ContainerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContainerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_docker_docker_common_proto_enumTypes[0].Descriptor()
}

func (ContainerStatus) Type() protoreflect.EnumType {
	return &file_proto_docker_docker_common_proto_enumTypes[0]
}

func (x ContainerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContainerStatus.Descriptor instead.
func (ContainerStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_docker_docker_common_proto_rawDescGZIP(), []int{0}
}

// Representación de un puerto expuesto por un contenedor.
type Port struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	PrivatePort   int32                  `protobuf:"varint,2,opt,name=private_port,json=privatePort,proto3" json:"private_port,omitempty"`
	PublicPort    int32                  `protobuf:"varint,3,opt,name=public_port,json=publicPort,proto3" json:"public_port,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"` // tcp, udp, sctp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Port) Reset() {
	*x = Port{}
	mi := &file_proto_docker_docker_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Port) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Port) ProtoMessage() {}

func (x *Port) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Port.ProtoReflect.Descriptor instead.
func (*Port) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_common_proto_rawDescGZIP(), []int{0}
}

func (x *Port) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Port) GetPrivatePort() int32 {
	if x != nil {
		return x.PrivatePort
	}
	return 0
}

func (x *Port) GetPublicPort() int32 {
	if x != nil {
		return x.PublicPort
	}
	return 0
}

func (x *Port) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// Variable de entorno en formato KEY=VALUE.
type EnvVar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvVar) Reset() {
	*x = EnvVar{}
	mi := &file_proto_docker_docker_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvVar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvVar) ProtoMessage() {}

func (x *EnvVar) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvVar.ProtoReflect.Descriptor instead.
func (*EnvVar) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_common_proto_rawDescGZIP(), []int{1}
}

func (x *EnvVar) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *EnvVar) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Montaje de volumen o bind mount.
type VolumeMount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"` // Ruta o nombre del volumen en el host
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"` // Ruta dentro del contenedor
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`     // bind, volume, tmpfs
	ReadOnly      bool                   `protobuf:"varint,4,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeMount) Reset() {
	*x = VolumeMount{}
	mi := &file_proto_docker_docker_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeMount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeMount) ProtoMessage() {}

func (x *VolumeMount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeMount.ProtoReflect.Descriptor instead.
func (*VolumeMount) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_common_proto_rawDescGZIP(), []int{2}
}

func (x *VolumeMount) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *VolumeMount) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *VolumeMount) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *VolumeMount) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

// Recursos básicos de un contenedor.
type ContainerResources struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemoryLimit   int64                  `protobuf:"varint,1,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"` // En bytes
	CpuLimit      float32                `protobuf:"fixed32,2,opt,name=cpu_limit,json=cpuLimit,proto3" json:"cpu_limit,omitempty"`         // Número de CPUs (0 = sin límite)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerResources) Reset() {
	*x = ContainerResources{}
	mi := &file_proto_docker_docker_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerResources) ProtoMessage() {}

func (x *ContainerResources) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerResources.ProtoReflect.Descriptor instead.
func (*ContainerResources) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_common_proto_rawDescGZIP(), []int{3}
}

func (x *ContainerResources) GetMemoryLimit() int64 {
	if x != nil {
		return x.MemoryLimit
	}
	return 0
}

func (x *ContainerResources) GetCpuLimit() float32 {
	if x != nil {
		return x.CpuLimit
	}
	return 0
}

// Etiquetas de un contenedor.
type Label struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Label) Reset() {
	*x = Label{}
	mi := &file_proto_docker_docker_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Label) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Label) ProtoMessage() {}

func (x *Label) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Label.ProtoReflect.Descriptor instead.
func (*Label) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_common_proto_rawDescGZIP(), []int{4}
}

func (x *Label) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Label) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_proto_docker_docker_common_proto protoreflect.FileDescriptor

const file_proto_docker_docker_common_proto_rawDesc = "" +
	"\n" +
	" proto/docker/docker_common.proto\x12\x12orchestrack.docker\"n\n" +
	"\x04Port\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12!\n" +
	"\fprivate_port\x18\x02 \x01(\x05R\vprivatePort\x12\x1f\n" +
	"\vpublic_port\x18\x03 \x01(\x05R\n" +
	"publicPort\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\"0\n" +
	"\x06EnvVar\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"n\n" +
	"\vVolumeMount\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1b\n" +
	"\tread_only\x18\x04 \x01(\bR\breadOnly\"T\n" +
	"\x12ContainerResources\x12!\n" +
	"\fmemory_limit\x18\x01 \x01(\x03R\vmemoryLimit\x12\x1b\n" +
	"\tcpu_limit\x18\x02 \x01(\x02R\bcpuLimit\"/\n" +
	"\x05Label\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value*\x84\x02\n" +
	"\x0fContainerStatus\x12 \n" +
	"\x1cCONTAINER_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18CONTAINER_STATUS_CREATED\x10\x01\x12\x1c\n" +
	"\x18CONTAINER_STATUS_RUNNING\x10\x02\x12\x1b\n" +
	"\x17CONTAINER_STATUS_PAUSED\x10\x03\x12\x1f\n" +
	"\x1bCONTAINER_STATUS_RESTARTING\x10\x04\x12\x1d\n" +
	"\x19CONTAINER_STATUS_REMOVING\x10\x05\x12\x1b\n" +
	"\x17CONTAINER_STATUS_EXITED\x10\x06\x12\x19\n" +
	"\x15CONTAINER_STATUS_DEAD\x10\aB7Z5github.com/go/orchestrack/backend/proto/docker;dockerb\x06proto3"

var (
	file_proto_docker_docker_common_proto_rawDescOnce sync.Once
	file_proto_docker_docker_common_proto_rawDescData []byte
)

func file_proto_docker_docker_common_proto_rawDescGZIP() []byte {
	file_proto_docker_docker_common_proto_rawDescOnce.Do(func() {
		file_proto_docker_docker_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_docker_docker_common_proto_rawDesc), len(file_proto_docker_docker_common_proto_rawDesc)))
	})
	return file_proto_docker_docker_common_proto_rawDescData
}

var file_proto_docker_docker_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_docker_docker_common_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_docker_docker_common_proto_goTypes = []any{
	(ContainerStatus)(0),       // 0: orchestrack.docker.ContainerStatus
	(*Port)(nil),               // 1: orchestrack.docker.Port
	(*EnvVar)(nil),             // 2: orchestrack.docker.EnvVar
	(*VolumeMount)(nil),        // 3: orchestrack.docker.VolumeMount
	(*ContainerResources)(nil), // 4: orchestrack.docker.ContainerResources
	(*Label)(nil),              // 5: orchestrack.docker.Label
}
var file_proto_docker_docker_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_docker_docker_common_proto_init() }
func file_proto_docker_docker_common_proto_init() {
	if File_proto_docker_docker_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_docker_docker_common_proto_rawDesc), len(file_proto_docker_docker_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_docker_docker_common_proto_goTypes,
		DependencyIndexes: file_proto_docker_docker_common_proto_depIdxs,
		EnumInfos:         file_proto_docker_docker_common_proto_enumTypes,
		MessageInfos:      file_proto_docker_docker_common_proto_msgTypes,
	}.Build()
	File_proto_docker_docker_common_proto = out.File
	file_proto_docker_docker_common_proto_goTypes = nil
	file_proto_docker_docker_common_proto_depIdxs = nil
}
