// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/docker/docker_image.proto

package docker

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DockerImageService_ListImages_FullMethodName  = "/orchestrack.docker.DockerImageService/ListImages"
	DockerImageService_PullImage_FullMethodName   = "/orchestrack.docker.DockerImageService/PullImage"
	DockerImageService_RemoveImage_FullMethodName = "/orchestrack.docker.DockerImageService/RemoveImage"
)

// DockerImageServiceClient is the client API for DockerImageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Servicio interno de `docker-service` para operaciones sobre imágenes Docker.
type DockerImageServiceClient interface {
	// Listar imágenes disponibles en el host.
	ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error)
	// Descargar una imagen del registry.
	PullImage(ctx context.Context, in *PullImageRequest, opts ...grpc.CallOption) (*PullImageResponse, error)
	// Eliminar una imagen del host.
	RemoveImage(ctx context.Context, in *RemoveImageRequest, opts ...grpc.CallOption) (*RemoveImageResponse, error)
}

type dockerImageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDockerImageServiceClient(cc grpc.ClientConnInterface) DockerImageServiceClient {
	return &dockerImageServiceClient{cc}
}

func (c *dockerImageServiceClient) ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListImagesResponse)
	err := c.cc.Invoke(ctx, DockerImageService_ListImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerImageServiceClient) PullImage(ctx context.Context, in *PullImageRequest, opts ...grpc.CallOption) (*PullImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PullImageResponse)
	err := c.cc.Invoke(ctx, DockerImageService_PullImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerImageServiceClient) RemoveImage(ctx context.Context, in *RemoveImageRequest, opts ...grpc.CallOption) (*RemoveImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveImageResponse)
	err := c.cc.Invoke(ctx, DockerImageService_RemoveImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DockerImageServiceServer is the server API for DockerImageService service.
// All implementations must embed UnimplementedDockerImageServiceServer
// for forward compatibility.
//
// Servicio interno de `docker-service` para operaciones sobre imágenes Docker.
type DockerImageServiceServer interface {
	// Listar imágenes disponibles en el host.
	ListImages(context.Context, *ListImagesRequest) (*ListImagesResponse, error)
	// Descargar una imagen del registry.
	PullImage(context.Context, *PullImageRequest) (*PullImageResponse, error)
	// Eliminar una imagen del host.
	RemoveImage(context.Context, *RemoveImageRequest) (*RemoveImageResponse, error)
	mustEmbedUnimplementedDockerImageServiceServer()
}

// UnimplementedDockerImageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDockerImageServiceServer struct{}

func (UnimplementedDockerImageServiceServer) ListImages(context.Context, *ListImagesRequest) (*ListImagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListImages not implemented")
}
func (UnimplementedDockerImageServiceServer) PullImage(context.Context, *PullImageRequest) (*PullImageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PullImage not implemented")
}
func (UnimplementedDockerImageServiceServer) RemoveImage(context.Context, *RemoveImageRequest) (*RemoveImageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveImage not implemented")
}
func (UnimplementedDockerImageServiceServer) mustEmbedUnimplementedDockerImageServiceServer() {}
func (UnimplementedDockerImageServiceServer) testEmbeddedByValue()                            {}

// UnsafeDockerImageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DockerImageServiceServer will
// result in compilation errors.
type UnsafeDockerImageServiceServer interface {
	mustEmbedUnimplementedDockerImageServiceServer()
}

func RegisterDockerImageServiceServer(s grpc.ServiceRegistrar, srv DockerImageServiceServer) {
	// If the following call panics, it indicates UnimplementedDockerImageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DockerImageService_ServiceDesc, srv)
}

func _DockerImageService_ListImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerImageServiceServer).ListImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerImageService_ListImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerImageServiceServer).ListImages(ctx, req.(*ListImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerImageService_PullImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerImageServiceServer).PullImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerImageService_PullImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerImageServiceServer).PullImage(ctx, req.(*PullImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerImageService_RemoveImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerImageServiceServer).RemoveImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerImageService_RemoveImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerImageServiceServer).RemoveImage(ctx, req.(*RemoveImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DockerImageService_ServiceDesc is the grpc.ServiceDesc for DockerImageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DockerImageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orchestrack.docker.DockerImageService",
	HandlerType: (*DockerImageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListImages",
			Handler:    _DockerImageService_ListImages_Handler,
		},
		{
			MethodName: "PullImage",
			Handler:    _DockerImageService_PullImage_Handler,
		},
		{
			MethodName: "RemoveImage",
			Handler:    _DockerImageService_RemoveImage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/docker/docker_image.proto",
}
