// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/docker/docker_image.proto

package docker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListImagesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Si es true, incluye imágenes intermedias (dangling).
	All bool `protobuf:"varint,1,opt,name=all,proto3" json:"all,omitempty"`
	// Filtros opcionales en formato clave=valor.
	Filters       []*Label `protobuf:"bytes,2,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListImagesRequest) Reset() {
	*x = ListImagesRequest{}
	mi := &file_proto_docker_docker_image_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListImagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListImagesRequest) ProtoMessage() {}

func (x *ListImagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_image_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListImagesRequest.ProtoReflect.Descriptor instead.
func (*ListImagesRequest) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_image_proto_rawDescGZIP(), []int{0}
}

func (x *ListImagesRequest) GetAll() bool {
	if x != nil {
		return x.All
	}
	return false
}

func (x *ListImagesRequest) GetFilters() []*Label {
	if x != nil {
		return x.Filters
	}
	return nil
}

type ListImagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Images        []*ImageSummary        `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListImagesResponse) Reset() {
	*x = ListImagesResponse{}
	mi := &file_proto_docker_docker_image_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListImagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListImagesResponse) ProtoMessage() {}

func (x *ListImagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_image_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListImagesResponse.ProtoReflect.Descriptor instead.
func (*ListImagesResponse) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_image_proto_rawDescGZIP(), []int{1}
}

func (x *ListImagesResponse) GetImages() []*ImageSummary {
	if x != nil {
		return x.Images
	}
	return nil
}

type PullImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         string                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"` // nombre:tag
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullImageRequest) Reset() {
	*x = PullImageRequest{}
	mi := &file_proto_docker_docker_image_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullImageRequest) ProtoMessage() {}

func (x *PullImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_image_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullImageRequest.ProtoReflect.Descriptor instead.
func (*PullImageRequest) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_image_proto_rawDescGZIP(), []int{2}
}

func (x *PullImageRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type PullImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         string                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullImageResponse) Reset() {
	*x = PullImageResponse{}
	mi := &file_proto_docker_docker_image_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullImageResponse) ProtoMessage() {}

func (x *PullImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_image_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullImageResponse.ProtoReflect.Descriptor instead.
func (*PullImageResponse) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_image_proto_rawDescGZIP(), []int{3}
}

func (x *PullImageResponse) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type RemoveImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // ID o name:tag
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	PruneChildren bool                   `protobuf:"varint,3,opt,name=prune_children,json=pruneChildren,proto3" json:"prune_children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveImageRequest) Reset() {
	*x = RemoveImageRequest{}
	mi := &file_proto_docker_docker_image_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveImageRequest) ProtoMessage() {}

func (x *RemoveImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_image_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveImageRequest.ProtoReflect.Descriptor instead.
func (*RemoveImageRequest) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_image_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveImageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RemoveImageRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *RemoveImageRequest) GetPruneChildren() bool {
	if x != nil {
		return x.PruneChildren
	}
	return false
}

type RemoveImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Deleted       []string               `protobuf:"bytes,2,rep,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveImageResponse) Reset() {
	*x = RemoveImageResponse{}
	mi := &file_proto_docker_docker_image_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveImageResponse) ProtoMessage() {}

func (x *RemoveImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_image_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveImageResponse.ProtoReflect.Descriptor instead.
func (*RemoveImageResponse) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_image_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveImageResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RemoveImageResponse) GetDeleted() []string {
	if x != nil {
		return x.Deleted
	}
	return nil
}

type ImagePulledEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImagePulledEvent) Reset() {
	*x = ImagePulledEvent{}
	mi := &file_proto_docker_docker_image_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImagePulledEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImagePulledEvent) ProtoMessage() {}

func (x *ImagePulledEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_image_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImagePulledEvent.ProtoReflect.Descriptor instead.
func (*ImagePulledEvent) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_image_proto_rawDescGZIP(), []int{6}
}

func (x *ImagePulledEvent) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ImagePulledEvent) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ImagePulledEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ImageRemovedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageRemovedEvent) Reset() {
	*x = ImageRemovedEvent{}
	mi := &file_proto_docker_docker_image_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageRemovedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageRemovedEvent) ProtoMessage() {}

func (x *ImageRemovedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_image_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageRemovedEvent.ProtoReflect.Descriptor instead.
func (*ImageRemovedEvent) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_image_proto_rawDescGZIP(), []int{7}
}

func (x *ImageRemovedEvent) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ImageRemovedEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ImageRemovedEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Resumen de una imagen Docker.
type ImageSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RepoTags      []string               `protobuf:"bytes,2,rep,name=repo_tags,json=repoTags,proto3" json:"repo_tags,omitempty"`
	Created       int64                  `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"` // Timestamp en segundos
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`       // Tamaño en bytes
	SharedSize    int64                  `protobuf:"varint,5,opt,name=shared_size,json=sharedSize,proto3" json:"shared_size,omitempty"`
	VirtualSize   int64                  `protobuf:"varint,6,opt,name=virtual_size,json=virtualSize,proto3" json:"virtual_size,omitempty"`
	Labels        []string               `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageSummary) Reset() {
	*x = ImageSummary{}
	mi := &file_proto_docker_docker_image_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageSummary) ProtoMessage() {}

func (x *ImageSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_image_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageSummary.ProtoReflect.Descriptor instead.
func (*ImageSummary) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_image_proto_rawDescGZIP(), []int{8}
}

func (x *ImageSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ImageSummary) GetRepoTags() []string {
	if x != nil {
		return x.RepoTags
	}
	return nil
}

func (x *ImageSummary) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *ImageSummary) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ImageSummary) GetSharedSize() int64 {
	if x != nil {
		return x.SharedSize
	}
	return 0
}

func (x *ImageSummary) GetVirtualSize() int64 {
	if x != nil {
		return x.VirtualSize
	}
	return 0
}

func (x *ImageSummary) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

var File_proto_docker_docker_image_proto protoreflect.FileDescriptor

const file_proto_docker_docker_image_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/docker/docker_image.proto\x12\x12orchestrack.docker\x1a proto/docker/docker_common.proto\"Z\n" +
	"\x11ListImagesRequest\x12\x10\n" +
	"\x03all\x18\x01 \x01(\bR\x03all\x123\n" +
	"\afilters\x18\x02 \x03(\v2\x19.orchestrack.docker.LabelR\afilters\"N\n" +
	"\x12ListImagesResponse\x128\n" +
	"\x06images\x18\x01 \x03(\v2 .orchestrack.docker.ImageSummaryR\x06images\"(\n" +
	"\x10PullImageRequest\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\")\n" +
	"\x11PullImageResponse\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\"a\n" +
	"\x12RemoveImageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\x12%\n" +
	"\x0eprune_children\x18\x03 \x01(\bR\rpruneChildren\"?\n" +
	"\x13RemoveImageResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\adeleted\x18\x02 \x03(\tR\adeleted\"e\n" +
	"\x10ImagePulledEvent\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"`\n" +
	"\x11ImageRemovedEvent\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"\xc5\x01\n" +
	"\fImageSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\trepo_tags\x18\x02 \x03(\tR\brepoTags\x12\x18\n" +
	"\acreated\x18\x03 \x01(\x03R\acreated\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x1f\n" +
	"\vshared_size\x18\x05 \x01(\x03R\n" +
	"sharedSize\x12!\n" +
	"\fvirtual_size\x18\x06 \x01(\x03R\vvirtualSize\x12\x16\n" +
	"\x06labels\x18\a \x03(\tR\x06labels2\xab\x02\n" +
	"\x12DockerImageService\x12[\n" +
	"\n" +
	"ListImages\x12%.orchestrack.docker.ListImagesRequest\x1a&.orchestrack.docker.ListImagesResponse\x12X\n" +
	"\tPullImage\x12$.orchestrack.docker.PullImageRequest\x1a%.orchestrack.docker.PullImageResponse\x12^\n" +
	"\vRemoveImage\x12&.orchestrack.docker.RemoveImageRequest\x1a'.orchestrack.docker.RemoveImageResponseB7Z5github.com/go/orchestrack/backend/proto/docker;dockerb\x06proto3"

var (
	file_proto_docker_docker_image_proto_rawDescOnce sync.Once
	file_proto_docker_docker_image_proto_rawDescData []byte
)

func file_proto_docker_docker_image_proto_rawDescGZIP() []byte {
	file_proto_docker_docker_image_proto_rawDescOnce.Do(func() {
		file_proto_docker_docker_image_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_docker_docker_image_proto_rawDesc), len(file_proto_docker_docker_image_proto_rawDesc)))
	})
	return file_proto_docker_docker_image_proto_rawDescData
}

var file_proto_docker_docker_image_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_docker_docker_image_proto_goTypes = []any{
	(*ListImagesRequest)(nil),   // 0: orchestrack.docker.ListImagesRequest
	(*ListImagesResponse)(nil),  // 1: orchestrack.docker.ListImagesResponse
	(*PullImageRequest)(nil),    // 2: orchestrack.docker.PullImageRequest
	(*PullImageResponse)(nil),   // 3: orchestrack.docker.PullImageResponse
	(*RemoveImageRequest)(nil),  // 4: orchestrack.docker.RemoveImageRequest
	(*RemoveImageResponse)(nil), // 5: orchestrack.docker.RemoveImageResponse
	(*ImagePulledEvent)(nil),    // 6: orchestrack.docker.ImagePulledEvent
	(*ImageRemovedEvent)(nil),   // 7: orchestrack.docker.ImageRemovedEvent
	(*ImageSummary)(nil),        // 8: orchestrack.docker.ImageSummary
	(*Label)(nil),               // 9: orchestrack.docker.Label
}
var file_proto_docker_docker_image_proto_depIdxs = []int32{
	9, // 0: orchestrack.docker.ListImagesRequest.filters:type_name -> orchestrack.docker.Label
	8, // 1: orchestrack.docker.ListImagesResponse.images:type_name -> orchestrack.docker.ImageSummary
	0, // 2: orchestrack.docker.DockerImageService.ListImages:input_type -> orchestrack.docker.ListImagesRequest
	2, // 3: orchestrack.docker.DockerImageService.PullImage:input_type -> orchestrack.docker.PullImageRequest
	4, // 4: orchestrack.docker.DockerImageService.RemoveImage:input_type -> orchestrack.docker.RemoveImageRequest
	1, // 5: orchestrack.docker.DockerImageService.ListImages:output_type -> orchestrack.docker.ListImagesResponse
	3, // 6: orchestrack.docker.DockerImageService.PullImage:output_type -> orchestrack.docker.PullImageResponse
	5, // 7: orchestrack.docker.DockerImageService.RemoveImage:output_type -> orchestrack.docker.RemoveImageResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_docker_docker_image_proto_init() }
func file_proto_docker_docker_image_proto_init() {
	if File_proto_docker_docker_image_proto != nil {
		return
	}
	file_proto_docker_docker_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_docker_docker_image_proto_rawDesc), len(file_proto_docker_docker_image_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_docker_docker_image_proto_goTypes,
		DependencyIndexes: file_proto_docker_docker_image_proto_depIdxs,
		MessageInfos:      file_proto_docker_docker_image_proto_msgTypes,
	}.Build()
	File_proto_docker_docker_image_proto = out.File
	file_proto_docker_docker_image_proto_goTypes = nil
	file_proto_docker_docker_image_proto_depIdxs = nil
}
