// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/docker/docker_events.proto

package docker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContainerCreatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerCreatedEvent) Reset() {
	*x = ContainerCreatedEvent{}
	mi := &file_proto_docker_docker_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerCreatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerCreatedEvent) ProtoMessage() {}

func (x *ContainerCreatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerCreatedEvent.ProtoReflect.Descriptor instead.
func (*ContainerCreatedEvent) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_events_proto_rawDescGZIP(), []int{0}
}

func (x *ContainerCreatedEvent) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ContainerCreatedEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContainerCreatedEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContainerCreatedEvent) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ContainerCreatedEvent) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ContainerStartedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerStartedEvent) Reset() {
	*x = ContainerStartedEvent{}
	mi := &file_proto_docker_docker_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerStartedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerStartedEvent) ProtoMessage() {}

func (x *ContainerStartedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerStartedEvent.ProtoReflect.Descriptor instead.
func (*ContainerStartedEvent) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_events_proto_rawDescGZIP(), []int{1}
}

func (x *ContainerStartedEvent) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ContainerStartedEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContainerStartedEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ContainerStoppedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerStoppedEvent) Reset() {
	*x = ContainerStoppedEvent{}
	mi := &file_proto_docker_docker_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerStoppedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerStoppedEvent) ProtoMessage() {}

func (x *ContainerStoppedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerStoppedEvent.ProtoReflect.Descriptor instead.
func (*ContainerStoppedEvent) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_events_proto_rawDescGZIP(), []int{2}
}

func (x *ContainerStoppedEvent) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ContainerStoppedEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContainerStoppedEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ContainerRestartedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerRestartedEvent) Reset() {
	*x = ContainerRestartedEvent{}
	mi := &file_proto_docker_docker_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerRestartedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerRestartedEvent) ProtoMessage() {}

func (x *ContainerRestartedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerRestartedEvent.ProtoReflect.Descriptor instead.
func (*ContainerRestartedEvent) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_events_proto_rawDescGZIP(), []int{3}
}

func (x *ContainerRestartedEvent) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ContainerRestartedEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContainerRestartedEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ContainerRenamedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	OldName       string                 `protobuf:"bytes,3,opt,name=old_name,json=oldName,proto3" json:"old_name,omitempty"`
	NewName       string                 `protobuf:"bytes,4,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerRenamedEvent) Reset() {
	*x = ContainerRenamedEvent{}
	mi := &file_proto_docker_docker_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerRenamedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerRenamedEvent) ProtoMessage() {}

func (x *ContainerRenamedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerRenamedEvent.ProtoReflect.Descriptor instead.
func (*ContainerRenamedEvent) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_events_proto_rawDescGZIP(), []int{4}
}

func (x *ContainerRenamedEvent) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ContainerRenamedEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContainerRenamedEvent) GetOldName() string {
	if x != nil {
		return x.OldName
	}
	return ""
}

func (x *ContainerRenamedEvent) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

func (x *ContainerRenamedEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ContainerRemovedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerRemovedEvent) Reset() {
	*x = ContainerRemovedEvent{}
	mi := &file_proto_docker_docker_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerRemovedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerRemovedEvent) ProtoMessage() {}

func (x *ContainerRemovedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerRemovedEvent.ProtoReflect.Descriptor instead.
func (*ContainerRemovedEvent) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_events_proto_rawDescGZIP(), []int{5}
}

func (x *ContainerRemovedEvent) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ContainerRemovedEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContainerRemovedEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContainerRemovedEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// ContainerEvent es un evento en tiempo real capturado del stream nativo
// de eventos de Docker Engine (die, oom, kill, health_status, restart, destroy).
type ContainerEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	ContainerId   string                 `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	ContainerName string                 `protobuf:"bytes,3,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	Image         string                 `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	EventType     string                 `protobuf:"bytes,5,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	ExitCode      int32                  `protobuf:"varint,6,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Reason        string                 `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`
	Timestamp     int64                  `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerEvent) Reset() {
	*x = ContainerEvent{}
	mi := &file_proto_docker_docker_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerEvent) ProtoMessage() {}

func (x *ContainerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerEvent.ProtoReflect.Descriptor instead.
func (*ContainerEvent) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_events_proto_rawDescGZIP(), []int{6}
}

func (x *ContainerEvent) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ContainerEvent) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ContainerEvent) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *ContainerEvent) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ContainerEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *ContainerEvent) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ContainerEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ContainerEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type AgentStatusEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentStatusEvent) Reset() {
	*x = AgentStatusEvent{}
	mi := &file_proto_docker_docker_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStatusEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStatusEvent) ProtoMessage() {}

func (x *AgentStatusEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docker_docker_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStatusEvent.ProtoReflect.Descriptor instead.
func (*AgentStatusEvent) Descriptor() ([]byte, []int) {
	return file_proto_docker_docker_events_proto_rawDescGZIP(), []int{7}
}

func (x *AgentStatusEvent) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *AgentStatusEvent) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AgentStatusEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AgentStatusEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AgentStatusEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_proto_docker_docker_events_proto protoreflect.FileDescriptor

const file_proto_docker_docker_events_proto_rawDesc = "" +
	"\n" +
	" proto/docker/docker_events.proto\x12\x12orchestrack.docker\"\x8f\x01\n" +
	"\x15ContainerCreatedEvent\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x04 \x01(\tR\x05image\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\"d\n" +
	"\x15ContainerStartedEvent\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"d\n" +
	"\x15ContainerStoppedEvent\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"f\n" +
	"\x17ContainerRestartedEvent\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"\x9a\x01\n" +
	"\x15ContainerRenamedEvent\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x19\n" +
	"\bold_name\x18\x03 \x01(\tR\aoldName\x12\x19\n" +
	"\bnew_name\x18\x04 \x01(\tR\anewName\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"x\n" +
	"\x15ContainerRemovedEvent\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\x81\x02\n" +
	"\x0eContainerEvent\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId\x12%\n" +
	"\x0econtainer_name\x18\x03 \x01(\tR\rcontainerName\x12\x14\n" +
	"\x05image\x18\x04 \x01(\tR\x05image\x12\x1d\n" +
	"\n" +
	"event_type\x18\x05 \x01(\tR\teventType\x12\x1b\n" +
	"\texit_code\x18\x06 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06reason\x18\a \x01(\tR\x06reason\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp\"\x9b\x01\n" +
	"\x10AgentStatusEvent\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reasonB7Z5github.com/go/orchestrack/backend/proto/docker;dockerb\x06proto3"

var (
	file_proto_docker_docker_events_proto_rawDescOnce sync.Once
	file_proto_docker_docker_events_proto_rawDescData []byte
)

func file_proto_docker_docker_events_proto_rawDescGZIP() []byte {
	file_proto_docker_docker_events_proto_rawDescOnce.Do(func() {
		file_proto_docker_docker_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_docker_docker_events_proto_rawDesc), len(file_proto_docker_docker_events_proto_rawDesc)))
	})
	return file_proto_docker_docker_events_proto_rawDescData
}

var file_proto_docker_docker_events_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_docker_docker_events_proto_goTypes = []any{
	(*ContainerCreatedEvent)(nil),   // 0: orchestrack.docker.ContainerCreatedEvent
	(*ContainerStartedEvent)(nil),   // 1: orchestrack.docker.ContainerStartedEvent
	(*ContainerStoppedEvent)(nil),   // 2: orchestrack.docker.ContainerStoppedEvent
	(*ContainerRestartedEvent)(nil), // 3: orchestrack.docker.ContainerRestartedEvent
	(*ContainerRenamedEvent)(nil),   // 4: orchestrack.docker.ContainerRenamedEvent
	(*ContainerRemovedEvent)(nil),   // 5: orchestrack.docker.ContainerRemovedEvent
	(*ContainerEvent)(nil),          // 6: orchestrack.docker.ContainerEvent
	(*AgentStatusEvent)(nil),        // 7: orchestrack.docker.AgentStatusEvent
}
var file_proto_docker_docker_events_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_docker_docker_events_proto_init() }
func file_proto_docker_docker_events_proto_init() {
	if File_proto_docker_docker_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_docker_docker_events_proto_rawDesc), len(file_proto_docker_docker_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_docker_docker_events_proto_goTypes,
		DependencyIndexes: file_proto_docker_docker_events_proto_depIdxs,
		MessageInfos:      file_proto_docker_docker_events_proto_msgTypes,
	}.Build()
	File_proto_docker_docker_events_proto = out.File
	file_proto_docker_docker_events_proto_goTypes = nil
	file_proto_docker_docker_events_proto_depIdxs = nil
}
